// src/pages/UserForm.tsx
import { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Save, User as UserIcon } from 'lucide-react';
import { getUserDetail, saveUser } from '../lib/api';
import { useToast } from '../components/Toast';
import type { SysUser } from '../types';

export default function UserForm({ overrideId }: { overrideId?: string }) {
  const navigate = useNavigate();
  const params = useParams();
  const id = overrideId || params.id;
  const isEdit = Boolean(id);
  const { showToast } = useToast();

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [dataLoaded, setDataLoaded] = useState(false);
  const [formData, setFormData] = useState<Partial<SysUser>>({
    name: '',
    phone: '',
    employeeNo: '',
    password: '',
    status: 1,
  });

  useEffect(() => {
    if (isEdit && id && !dataLoaded) {
      setDataLoaded(true);
      loadUser(parseInt(id));
    }
  }, [id, dataLoaded]);

  const loadUser = async (userId: number) => {
    setLoading(true);
    try {
      const data = await getUserDetail(userId);
      if (data) {
        // 编辑时不清空密码
        const { password, ...rest } = data;
        setFormData({ ...rest, password: '' });
      }
    } catch (error) {
      console.error('Failed to load user:', error);
    } finally {
      setLoading(false);
    }
  };

  const canSave = () => {
    if (!formData.name || !formData.phone || !formData.employeeNo) {
      return false;
    }
    // 新增时密码必填
    if (!isEdit && !formData.password) {
      return false;
    }
    return true;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!canSave()) {
      showToast('请填写必填项', 'error');
      return;
    }

    setSaving(true);
    try {
      await saveUser(formData);
      showToast(isEdit ? '更新成功' : '创建成功', 'success');
      navigate('/users');
    } catch (error: any) {
      showToast(error?.message || '保存失败', 'error');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="p-6 flex items-center justify-center h-full">
        <div className="text-[var(--text-muted)]">加载中...</div>
      </div>
    );
  }

  return (
    <div>
      {/* 标题 */}
      <div className="flex items-center gap-3 mb-6">
        <button
          onClick={() => navigate('/users')}
          className="p-2 hover:bg-[var(--bg-hover-light)] rounded-lg text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <div className="flex items-center gap-3">
          <UserIcon className="w-6 h-6 text-[var(--accent)]" />
          <h1 className="text-xl font-bold text-[var(--text-primary)]">{isEdit ? '编辑用户' : '新增用户'}</h1>
        </div>
      </div>

      {/* 表单 */}
      <form onSubmit={handleSubmit}>
        <div className="bg-[var(--bg-secondary)] rounded-xl border border-[var(--border)] p-6 mb-4">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-1 h-5 bg-[var(--accent)] rounded-full"></div>
            <h3 className="text-base font-medium text-[var(--accent)]">基本信息</h3>
          </div>
          <div className="grid grid-cols-2 gap-6">
            {/* 姓名 */}
            <div>
              <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">
                姓名 <span className="text-[var(--danger)]">*</span>
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder="请输入姓名"
                className="w-full px-4 py-2.5 bg-[var(--input-bg)] border border-[var(--input-border)] rounded-lg focus:outline-none focus:border-[var(--accent)] text-[var(--text-input)] placeholder:text-[var(--text-muted)] transition-colors"
              />
            </div>

            {/* 工号 */}
            <div>
              <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">
                工号 <span className="text-[var(--danger)]">*</span>
              </label>
              <input
                type="text"
                value={formData.employeeNo}
                onChange={(e) => setFormData({ ...formData, employeeNo: e.target.value })}
                placeholder="请输入工号"
                className="w-full px-4 py-2.5 bg-[var(--input-bg)] border border-[var(--input-border)] rounded-lg focus:outline-none focus:border-[var(--accent)] text-[var(--text-input)] placeholder:text-[var(--text-muted)] transition-colors"
              />
            </div>

            {/* 手机号 */}
            <div>
              <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">
                手机号 <span className="text-[var(--danger)]">*</span>
              </label>
              <input
                type="text"
                value={formData.phone}
                onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                placeholder="请输入手机号"
                className="w-full px-4 py-2.5 bg-[var(--input-bg)] border border-[var(--input-border)] rounded-lg focus:outline-none focus:border-[var(--accent)] text-[var(--text-input)] placeholder:text-[var(--text-muted)] transition-colors"
              />
            </div>

            {/* 状态 */}
            <div>
              <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">
                状态 <span className="text-[var(--danger)]">*</span>
              </label>
              <select
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: Number(e.target.value) })}
                className="w-full px-4 py-2.5 bg-[var(--input-bg)] border border-[var(--input-border)] rounded-lg focus:outline-none focus:border-[var(--accent)] text-[var(--text-input)] transition-colors"
              >
                <option value={1}>启用</option>
                <option value={0}>禁用</option>
              </select>
            </div>

            {/* 密码 */}
            <div>
              <label className="block text-sm font-medium text-[var(--text-secondary)] mb-2">
                密码 <span className="text-[var(--danger)]">{isEdit ? '' : '*'}</span>
              </label>
              <input
                type="password"
                value={formData.password}
                onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                placeholder={isEdit ? '不修改请留空' : '请输入密码'}
                className="w-full px-4 py-2.5 bg-[var(--input-bg)] border border-[var(--input-border)] rounded-lg focus:outline-none focus:border-[var(--accent)] text-[var(--text-input)] placeholder:text-[var(--text-muted)] transition-colors"
              />
            </div>
          </div>
        </div>

        {/* 底部按钮 */}
        <div className="flex justify-end mt-6">
          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => navigate('/users')}
              className="px-6 py-2.5 bg-[var(--bg-tertiary)] text-[var(--text-primary)] rounded-lg hover:bg-[var(--bg-hover)] transition-colors"
            >
              返回
            </button>
            <button
              type="submit"
              disabled={saving || !canSave()}
              className="flex items-center gap-2 px-6 py-2.5 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg transition-colors disabled:opacity-50"
            >
              <Save className="w-4 h-4" />
              {saving ? '保存中...' : '保存'}
            </button>
          </div>
        </div>
      </form>
    </div>
  );
}

// src-vue/pages/users/UserForm.vue
<template>
  <div class="p-6">
    <!-- 标题 -->
    <div class="flex items-center gap-3 mb-6">
      <el-button text @click="router.back()">
        <el-icon size="20"><ArrowLeft /></el-icon>
      </el-button>
      <div class="flex items-center gap-3">
        <el-icon size="24" color="var(--accent)"><User /></el-icon>
        <h1 class="text-xl font-bold">{{ isEdit ? '编辑用户' : '新增用户' }}</h1>
      </div>
    </div>

    <!-- 表单 -->
    <div class="bg-[var(--bg-secondary)]00 rounded-xl border border-[var(--border-light)]00 p-6">
      <el-form :model="formData" label-position="top" class="max-w-2xl">
        <div class="mb-4">
          <div class="flex items-center gap-2 mb-4">
            <div class="w-1 h-5 bg-[var(--accent)] rounded-full"></div>
            <h3 class="text-base font-medium text-[var(--accent)]">基本信息</h3>
          </div>
        </div>

        <el-row :gutter="24">
          <el-col :span="12">
            <el-form-item label="姓名" required>
              <el-input v-model="formData.name" placeholder="请输入姓名" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="工号" required>
              <el-input v-model="formData.employeeNo" placeholder="请输入工号" :disabled="isEdit" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="24">
          <el-col :span="12">
            <el-form-item label="手机号" required>
              <el-input v-model="formData.phone" placeholder="请输入手机号" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="状态" required>
              <el-select v-model="formData.status" class="w-full">
                <el-option label="启用" :value="1" />
                <el-option label="禁用" :value="0" />
              </el-select>
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="24">
          <el-col :span="12">
            <el-form-item :label="isEdit ? '密码（不修改请留空）' : '密码'">
              <el-input
                v-model="formData.password"
                type="password"
                :placeholder="isEdit ? '不修改请留空' : '请输入密码'"
                show-password
              />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>

      <!-- 底部按钮 -->
      <div class="flex justify-end mt-6 gap-3">
        <el-button @click="router.back()">返回</el-button>
        <el-button type="primary" :loading="saving" @click="handleSubmit">保存</el-button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ArrowLeft, User } from '@element-plus/icons-vue'
import { getUserDetail, saveUser } from '@/lib/api'

interface SysUser {
  id?: number
  name: string
  phone: string
  employeeNo: string
  password?: string
  status?: number
}

const router = useRouter()
const route = useRoute()

const id = computed(() => route.params.id as string | undefined)
const isEdit = computed(() => Boolean(id.value && id.value !== 'new'))

const loading = ref(false)
const saving = ref(false)
const formData = ref<SysUser>({
  name: '',
  phone: '',
  employeeNo: '',
  password: '',
  status: 1,
})

async function loadUser(userId: number) {
  loading.value = true
  try {
    const data = await getUserDetail(userId)
    if (data) {
      // 编辑时不清空密码
      const { password, ...rest } = data
      formData.value = { ...rest, password: '' }
    }
  } catch (error) {
    console.error('Failed to load user:', error)
  } finally {
    loading.value = false
  }
}

function canSave(): boolean {
  if (!formData.value.name || !formData.value.phone || !formData.value.employeeNo) {
    return false
  }
  // 新增时密码必填
  if (!isEdit.value && !formData.value.password) {
    return false
  }
  return true
}

async function handleSubmit() {
  if (!canSave()) {
    ElMessage.warning('请填写必填项')
    return
  }

  saving.value = true
  try {
    await saveUser(formData.value)
    ElMessage.success(isEdit.value ? '更新成功' : '创建成功')
    router.push('/users')
  } catch (error: any) {
    ElMessage.error(error?.message || '保存失败')
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  if (isEdit.value && id.value) {
    loadUser(parseInt(id.value))
  }
})
</script>
