// src-vue/components/editor/ComponentPanel.vue
<template>
  <div class="component-panel p-4">
    <h4 class="text-sm text-[var(--text-muted)] mb-4 font-medium">组件库</h4>
    
    <div v-for="category in componentCategories" :key="category.name" class="mb-5">
      <div class="text-xs text-[var(--text-muted)] mb-2 px-1">{{ category.name }}</div>
      <div class="flex flex-col gap-1.5">
        <div
          v-for="comp in category.components"
          :key="comp.type"
          class="flex items-center gap-2 p-2.5 bg-[var(--bg-table-header)] rounded-md text-sm cursor-grab transition-colors hover:bg-[var(--bg-tertiary)] active:cursor-grabbing select-none"
          draggable="true"
          @dragstart="onDragStart($event, comp)"
        >
          <span class="text-[var(--text-secondary)]">{{ comp.label }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
interface ComponentItem {
  type: string
  label: string
  icon: string
  defaultProps?: Record<string, unknown>
}

interface ComponentCategory {
  name: string
  components: ComponentItem[]
}

const emit = defineEmits<{
  'drag-start': [event: DragEvent, type: string, label: string, defaultProps?: Record<string, unknown>]
}>()

const componentCategories: ComponentCategory[] = [
  {
    name: '基础组件',
    components: [
      { type: 'text', label: '文本', icon: 'Text', defaultProps: { content: '这是一段文本' } },
      { type: 'button', label: '按钮', icon: 'Button', defaultProps: { text: '按钮', buttonType: 'primary' } },
      { type: 'image', label: '图片', icon: 'Picture', defaultProps: { src: '', alt: '图片' } },
      { type: 'link', label: '链接', icon: 'Link', defaultProps: { text: '链接', url: '#' } },
    ],
  },
  {
    name: '表单组件',
    components: [
      { type: 'input', label: '输入框', icon: 'Edit', defaultProps: { placeholder: '请输入', label: '输入框' } },
      { type: 'select', label: '下拉框', icon: 'Document', defaultProps: { placeholder: '请选择', label: '下拉框', options: ['选项1', '选项2', '选项3'] } },
      { type: 'date', label: '日期选择', icon: 'Calendar', defaultProps: { placeholder: '请选择日期', label: '日期选择' } },
      { type: 'switch', label: '开关', icon: 'Open', defaultProps: { label: '开关', value: false } },
      { type: 'slider', label: '滑动条', icon: 'DCaret', defaultProps: { label: '滑动条', min: 0, max: 100, value: 50 } },
    ],
  },
  {
    name: '数据组件',
    components: [
      { type: 'table', label: '表格', icon: 'Grid', defaultProps: { title: '数据表格' } },
      { type: 'lineChart', label: '折线图', icon: 'DataLine', defaultProps: { title: '折线图' } },
      { type: 'barChart', label: '柱状图', icon: 'Histogram', defaultProps: { title: '柱状图' } },
      { type: 'pieChart', label: '饼图', icon: 'PieChart', defaultProps: { title: '饼图' } },
    ],
  },
  {
    name: '布局组件',
    components: [
      { type: 'card', label: '卡片', icon: 'Menu', defaultProps: { title: '卡片标题' } },
      { type: 'tabs', label: '标签页', icon: 'Menu', defaultProps: { tabs: ['标签页1', '标签页2'], activeTab: 0 } },
      { type: 'collapse', label: '折叠面板', icon: 'Menu', defaultProps: { title: '折叠面板标题' } },
      { type: 'grid', label: '栅格', icon: 'Menu', defaultProps: { cols: 3, gap: 10 } },
      { type: 'divider', label: '分割线', icon: 'Minus', defaultProps: { direction: 'horizontal' } },
      { type: 'blank', label: '空白', icon: 'View', defaultProps: { height: 50 } },
    ],
  },
]

function onDragStart(event: DragEvent, comp: ComponentItem) {
  console.log('[ComponentPanel] onDragStart:', comp.type, comp.label)
  if (event.dataTransfer) {
    const dragData = {
      fromPalette: true,
      type: comp.type,
      label: comp.label,
      defaultProps: comp.defaultProps || {},
    }
    console.log('[ComponentPanel] setting dataTransfer:', JSON.stringify(dragData))
    event.dataTransfer.setData('application/json', JSON.stringify(dragData))
    event.dataTransfer.effectAllowed = 'copy'
  }
  emit('drag-start', event, comp.type, comp.label, comp.defaultProps)
}
</script>

<style scoped>
.component-panel {
  height: 100%;
  overflow-y: auto;
  background: var(--bg-secondary);
  user-select: none;
}
</style>

// src/pages/editor/ComponentPanel.tsx
import React from 'react';
import { Box } from 'lucide-react';
import { ComponentItem } from './types';
import { componentCategories, iconMap } from './constants';

interface ComponentPanelProps {
  onDragStart: (comp: ComponentItem) => void;
}

// Component Panel - Left Side
function ComponentPanel({ onDragStart }: ComponentPanelProps) {
  const handleDragStart = (e: React.DragEvent, comp: ComponentItem) => {
    e.dataTransfer.setData('application/json', JSON.stringify({
      type: comp.type,
      label: comp.label,
      fromPalette: true,
      defaultProps: comp.defaultProps || {},
    }));
    e.dataTransfer.effectAllowed = 'copy';
    onDragStart(comp);
  };

  return (
    <div className="h-full bg-[var(--bg-primary)] overflow-y-auto">
      <div className="p-4">
        <h3 className="text-sm font-medium text-[var(--text-primary)] mb-4">组件库</h3>
        
        {componentCategories.map((category) => (
          <div key={category.name} className="mb-6">
            <div className="text-xs text-[var(--text-muted)] mb-2 px-1">{category.name}</div>
            <div className="flex flex-col gap-1.5">
              {category.components.map((comp) => {
                const IconComp = iconMap[comp.icon] || Box;
                return (
                  <div
                    key={comp.type}
                    draggable
                    onDragStart={(e) => handleDragStart(e, comp)}
                    className="flex items-center gap-2 px-3 py-2 bg-[var(--bg-tertiary)] rounded-md text-sm cursor-grab hover:bg-[var(--bg-hover)] active:cursor-grabbing transition-colors select-none text-[var(--text-primary)]"
                  >
                    <IconComp className="w-4 h-4 text-[var(--text-muted)]" />
                    <span>{comp.label}</span>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default ComponentPanel;
