// src/components/editor/ComponentPanel.vue
<template>
  <div class="component-panel">
    <div class="px-4 py-3 border-b border-[var(--border-light)]">
      <h4 class="text-sm font-medium text-[var(--text-primary)]">组件库</h4>
      <p class="text-xs text-[var(--text-muted)] mt-1">拖拽组件到画布</p>
    </div>

    <div class="p-2 overflow-y-auto flex-1">
    <div v-for="category in componentCategories" :key="category.name" class="mb-4">
      <div class="text-xs text-[var(--text-muted)] mb-2 px-2 font-medium uppercase tracking-wide">{{ category.name }}</div>
      <div class="flex flex-col gap-1">
        <div
          v-for="comp in category.components"
          :key="comp.type"
          class="component-item flex items-center gap-3 p-3 rounded-lg cursor-grab transition-all duration-150 hover:translate-x-1 active:cursor-grabbing select-none group"
          draggable="true"
          @dragstart="onDragStart($event, comp)"
        >
          <div class="w-8 h-8 rounded-md bg-[var(--bg-tertiary)] flex items-center justify-center text-sm group-hover:bg-[var(--accent)] group-hover:text-white transition-colors">
            {{ getComponentIcon(comp.type) }}
          </div>
          <span class="text-sm text-[var(--text-primary)] font-medium">{{ comp.label }}</span>
        </div>
      </div>
    </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { getComponentCategories, getComponentIcon } from '@/pages/editor/component-registry'
import type { ComponentCategory } from '@/pages/editor/types'

interface ComponentItem {
  type: string
  label: string
  icon: string
  defaultProps?: Record<string, unknown>
}

const emit = defineEmits<{
  'drag-start': [event: DragEvent, type: string, label: string, defaultProps?: Record<string, unknown>]
}>()

const componentCategories = getComponentCategories()

function onDragStart(event: DragEvent, comp: ComponentItem) {
  console.log('[ComponentPanel] onDragStart:', comp.type, comp.label)
  if (event.dataTransfer) {
    const dragData = {
      fromPalette: true,
      type: comp.type,
      label: comp.label,
      defaultProps: comp.defaultProps || {},
    }
    console.log('[ComponentPanel] setting dataTransfer:', JSON.stringify(dragData))
    event.dataTransfer.setData('application/json', JSON.stringify(dragData))
    event.dataTransfer.effectAllowed = 'copy'
  }
  emit('drag-start', event, comp.type, comp.label, comp.defaultProps)
}
</script>

<style scoped>
.component-panel {
  height: 100%;
  display: flex;
  flex-direction: column;
  background: var(--bg-secondary);
  user-select: none;
}

.component-item {
  background: var(--bg-primary);
  border: 1px solid transparent;
}

.component-item:hover {
  border-color: var(--accent);
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
}

.component-item:active {
  transform: scale(0.98);
}
</style>

// src/pages/editor/ComponentPanel.tsx
import React from 'react';
import { Box } from 'lucide-react';
import { ComponentItem } from './types';
import { componentCategories, iconMap } from './constants';

interface ComponentPanelProps {
  onDragStart: (comp: ComponentItem) => void;
}

// Component Panel - Left Side
function ComponentPanel({ onDragStart }: ComponentPanelProps) {
  const handleDragStart = (e: React.DragEvent, comp: ComponentItem) => {
    e.dataTransfer.setData('application/json', JSON.stringify({
      type: comp.type,
      label: comp.label,
      fromPalette: true,
      defaultProps: comp.defaultProps || {},
    }));
    e.dataTransfer.effectAllowed = 'copy';
    onDragStart(comp);
  };

  return (
    <div className="h-full bg-[var(--bg-primary)] overflow-y-auto">
      <div className="p-4">
        <h3 className="text-sm font-medium text-[var(--text-primary)] mb-4">组件库</h3>
        
        {componentCategories.map((category) => (
          <div key={category.name} className="mb-6">
            <div className="text-xs text-[var(--text-muted)] mb-2 px-1">{category.name}</div>
            <div className="flex flex-col gap-1.5">
              {category.components.map((comp) => {
                const IconComp = iconMap[comp.icon] || Box;
                return (
                  <div
                    key={comp.type}
                    draggable
                    onDragStart={(e) => handleDragStart(e, comp)}
                    className="flex items-center gap-2 px-3 py-2 bg-[var(--bg-tertiary)] rounded-md text-sm cursor-grab hover:bg-[var(--bg-hover)] active:cursor-grabbing transition-colors select-none text-[var(--text-primary)]"
                  >
                    <IconComp className="w-4 h-4 text-[var(--text-muted)]" />
                    <span>{comp.label}</span>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default ComponentPanel;
