// src/pages/editor/DropCanvas.vue
<template>
  <div
    ref="canvasRef"
    class="min-h-0 w-full overflow-y-auto p-4 transition-colors"
    :class="{ 'bg-[var(--accent-light)] border-2 border-dashed border-[var(--accent)]': isDragOver }"
    @dragover.prevent="onDragOver"
    @dragleave="onDragLeave"
    @drop="onDrop"
    @click="onCanvasClick"
  >
    <!-- Empty state -->
    <div
      v-if="components.length === 0"
      class="flex items-center justify-center min-h-[400px] min-w-[1280px] bg-[var(--bg-primary)] border-2 border-dashed border-[var(--border)] rounded-lg"
    >
      <div class="text-center text-[var(--text-muted)]">
        <div class="text-4xl mb-2">📦</div>
        <div>拖拽组件到此处构建页面</div>
      </div>
    </div>

    <!-- Components list -->
    <div v-else class="flex flex-col gap-3 min-w-[1280px]">
      <div
        v-for="(comp, index) in components"
        :key="comp.id"
        draggable
        class="relative bg-[var(--bg-primary)] border-2 rounded-md transition-all cursor-pointer group"
        :class="[
          selectedId === comp.id
            ? 'border-[var(--accent)] shadow-lg ring-2 ring-[var(--accent-light)]'
            : 'border-transparent hover:border-[var(--border)]'
        ]"
        @dragstart="onRootDragStart($event, index)"
        @dragover.prevent
        @click.stop="onComponentClick(comp.id)"
        @dblclick.stop="onComponentDoubleClick(comp.id)"
      >
        <!-- Component actions toolbar -->
        <div class="absolute -top-3 right-2 opacity-0 group-hover:opacity-100 transition-opacity z-10 bg-[var(--bg-primary)] rounded shadow flex items-center gap-1 p-1">
          <!-- Up/Down for root components only -->
          <button
            v-if="!isNested(comp)"
            @click.stop="moveUp(index)"
            :disabled="index === 0"
            class="p-1 border border-[var(--border)] rounded hover:bg-[var(--bg-hover)] disabled:opacity-30"
            title="上移"
          >
            <ArrowUp class="w-3 h-3" />
          </button>
          <button
            v-if="!isNested(comp)"
            @click.stop="moveDown(index)"
            :disabled="index === components.length - 1"
            class="p-1 border border-[var(--border)] rounded hover:bg-[var(--bg-hover)] disabled:opacity-30"
            title="下移"
          >
            <ArrowDown class="w-3 h-3" />
          </button>
          <!-- Delete button -->
          <button
            @click.stop="onDelete(comp.id)"
            class="p-1 border border-[var(--danger)]/30 rounded hover:bg-[var(--danger)]/10 text-[var(--danger)]"
            :title="isNested(comp) ? '移除' : '删除'"
          >
            <Trash2 class="w-3 h-3" />
          </button>
          <!-- Drag handle -->
          <div class="p-1 border border-[var(--border)] rounded text-[var(--text-muted)] cursor-grab" title="拖拽">
            <GripVertical class="w-3 h-3" />
          </div>
        </div>

        <!-- Component content -->
        <div class="p-2">
          <!-- Container type: render container structure (children handled by ComponentRenderer in canvasMode) -->
          <template v-if="isContainerType(comp.type)">
            <div
              class="min-h-16 border-2 border-dashed rounded m-2 p-2 transition-colors"
              :class="[
                dragOverContainerId === comp.id
                  ? 'border-[var(--accent)] bg-[var(--accent-light)]'
                  : 'border-[var(--border)] bg-[var(--bg-secondary)] hover:border-[var(--accent)]'
              ]"
              @dragover.prevent="onContainerDragOver($event, comp.id)"
              @dragleave="onContainerDragLeave"
              @drop.prevent="onContainerDrop($event, comp.id)"
              @click.stop="onComponentClick(comp.id)"
              @dblclick.stop="onComponentDoubleClick(comp.id)"
            >
              <ComponentRenderer
                :component="comp"
                :editable="true"
                canvas-mode
                :show-children="getContainerChildren(comp)"
                :container-id="comp.id"
                @remove-child="(containerId, childId) => removeFromContainer(containerId, childId)"
                @drag-start-nested="onNestedDragStart"
                @select="onComponentClick"
                @drop-on-tab="onDropOnTab"
                @open-props="(id: string) => emit('open-props', id)"
              />
            </div>
          </template>
          <!-- Regular component -->
          <template v-else>
            <ComponentRenderer :component="comp" :editable="true" canvas-mode @select="onComponentClick" @open-props="(id: string) => emit('open-props', id)" />
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ArrowUp, ArrowDown, Trash2, GripVertical } from 'lucide-vue-next'
import ComponentRenderer from './ComponentRenderer.vue'
import type { CanvasComponent, TabItem } from './types'

interface Props {
  components: CanvasComponent[]
  selectedId?: string | null
}

const props = withDefaults(defineProps<Props>(), {
  selectedId: null
})

const emit = defineEmits<{
  select: [id: string | null]
  reorder: [fromIndex: number, toIndex: number]
  delete: [id: string]
  drop: [data: { fromPalette: boolean, type?: string, label?: string, defaultProps?: Record<string, unknown> } | null]
  'add-child': [containerId: string, component: CanvasComponent, insertIndex: number, tabIndex?: number]
  'remove-child': [containerId: string, childId: string]
  'move-child-to-root': [containerId: string, childId: string, insertIndex: number, tabIndex?: number]
  'update-component': [id: string, key: string, value: any]
  'drag-start': []
  'drag-end': []
  'open-props': [id: string]
}>()

const canvasRef = ref<HTMLElement | null>(null)
const isDragOver = ref(false)
const dragOverContainerId = ref<string | null>(null)
const dragOverIndex = ref<number>(0)  // Track insert position within container
const isDroppingToTab = ref(false)  // Guard: prevent onContainerDrop after onDropOnTab

// Drag state
const dragState = ref<{
  dragType: 'new' | 'reorder' | 'nested'
  sourceContainerId: string | null
  sourceIndex: number
}>({
  dragType: 'new',
  sourceContainerId: null,
  sourceIndex: -1,
})

// Container types that support nested children
const isContainerType = (type: string) => type === 'card' || type === 'tabs' || type === 'collapse'

// Check if component is nested (inside a container)
const isNested = (comp: CanvasComponent) => false // Root level only

// Get children for a container component
const getContainerChildren = (comp: CanvasComponent): CanvasComponent[] => {
  if (comp.type === 'tabs') {
    const activeTabId = comp.props?.activeTab as string || 'tab_0'
    // Filter children by tabId (new flat design: child.tabId indicates which tab it belongs to)
    return (comp.children || []).filter(c => (c as any).tabId === activeTabId)
  }
  return comp.children || []
}

// Check if targetId is the same as or a descendant of sourceId (prevents dropping container into itself)
const isDescendantOf = (targetId: string, sourceId: string): boolean => {
  if (targetId === sourceId) return true
  const findComponent = (comps: CanvasComponent[], id: string): CanvasComponent | null => {
    for (const c of comps) {
      if (c.id === id) return c
      if (c.children?.length) {
        const found = findComponent(c.children, id)
        if (found) return found
      }
    }
    return null
  }
  const source = findComponent(props.components, sourceId)
  if (!source) return false
  // Check if targetId is in source's descendants
  const checkDescendants = (comp: CanvasComponent): boolean => {
    if (comp.id === targetId) return true
    return comp.children?.some(checkDescendants) || false
  }
  return checkDescendants(source)
}

// Generate unique ID
const generateId = () => Date.now()

// Event handlers
const onDragOver = (e: DragEvent) => {
  e.preventDefault()
  console.log('[DropCanvas] onDragOver called')
  isDragOver.value = true
}

const onDragLeave = (e: DragEvent) => {
  const rect = canvasRef.value?.getBoundingClientRect()
  if (rect) {
    const { clientX, clientY } = e
    if (clientX < rect.left || clientX > rect.right || clientY < rect.top || clientY > rect.bottom) {
      isDragOver.value = false
    }
  }
}

const onDrop = (e: DragEvent) => {
  e.preventDefault()
  e.stopPropagation()
  isDragOver.value = false
  dragOverContainerId.value = null
  
  console.log('[DropCanvas] onDrop called')
  
  // Parse drop data before emitting
  const data = e.dataTransfer?.getData('application/json')
  console.log('[DropCanvas] dataTransfer:', data)
  
  let parsed = null
  if (data) {
    try {
      parsed = JSON.parse(data)
      console.log('[DropCanvas] parsed:', parsed)
    } catch (err) {
      console.error('Failed to parse drop data:', err)
    }
  }
  emit('drop', parsed)
  emit('drag-end')
}

const onCanvasClick = () => {
  emit('select', null)
}

const onComponentClick = (id: string) => {
  emit('select', id)
}

// Double-click to open props panel
const onComponentDoubleClick = (id: string) => {
  emit('open-props', id)
}

// Move component up
const moveUp = (index: number) => {
  if (index > 0) {
    emit('reorder', index, index - 1)
  }
}

// Move component down
const moveDown = (index: number) => {
  if (index < props.components.length - 1) {
    emit('reorder', index, index + 1)
  }
}

// Delete component
const onDelete = (id: string) => {
  emit('delete', id)
}

// Drag from palette (new component)
const onPaletteDragStart = (e: DragEvent, type: string, label: string, defaultProps?: Record<string, unknown>) => {
  dragState.value = {
    dragType: 'new',
    sourceContainerId: null,
    sourceIndex: -1,
  }
  e.dataTransfer?.setData('application/json', JSON.stringify({
    fromPalette: true,
    type,
    label,
    defaultProps,
  }))
}

// Drag from root component (reorder)
const onRootDragStart = (e: DragEvent, index: number) => {
  emit('drag-start')
  dragState.value = {
    dragType: 'reorder',
    sourceContainerId: null,
    sourceIndex: index,
  }
  e.dataTransfer?.setData('application/json', JSON.stringify({
    fromRoot: true,
    index,
  }))
}

// Drag from nested component (move out of container)
const onNestedDragStart = (e: DragEvent, containerId: string, index: number) => {
  emit('drag-start')
  dragState.value = {
    dragType: 'nested',
    sourceContainerId: containerId,
    sourceIndex: index,
  }
  e.dataTransfer?.setData('application/json', JSON.stringify({
    fromNested: true,
    containerId,
    index,
  }))
}

// Container drag over
// Calculate insert index based on mouse Y position within container
const calcInsertIndex = (e: DragEvent, containerId: string): number => {
  const containerEl = (e.currentTarget as HTMLElement)
  const children = getContainerChildren(props.components.find(c => c.id === containerId)!)
  if (children.length === 0) return 0
  
  const containerRect = containerEl.getBoundingClientRect()
  const relY = e.clientY - containerRect.top
  
  // Find the child element under mouse
  const childEls = containerEl.querySelectorAll('[data-child-index]')
  for (const childEl of childEls) {
    const rect = childEl.getBoundingClientRect()
    const midY = rect.top + rect.height / 2 - containerRect.top
    if (relY < midY) {
      return parseInt((childEl as HTMLElement).dataset.childIndex || '0', 10)
    }
  }
  return children.length
}

const onContainerDragOver = (e: DragEvent, containerId: string) => {
  e.preventDefault()
  e.stopPropagation()
  dragOverContainerId.value = containerId
  dragOverIndex.value = calcInsertIndex(e, containerId)
}

const onContainerDragLeave = (e: DragEvent) => {
  e.stopPropagation()
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
  const { clientX, clientY } = e
  if (clientX < rect.left || clientX > rect.right || clientY < rect.top || clientY > rect.bottom) {
    dragOverContainerId.value = null
  }
}

// Drop on a specific tab within a tabs container
const onDropOnTab = (containerId: string, tabIndex: number, data: any) => {
  console.log('[DropCanvas] onDropOnTab called:', { containerId, tabIndex, data })
  isDroppingToTab.value = true // Guard: prevent onContainerDrop from running after this
  
  try {
    // Check if trying to drop a container into itself
    if (data.fromRoot) {
      const comp = props.components[data.index]
      if (comp && isContainerType(comp.type) && isDescendantOf(containerId, comp.id)) {
        console.warn('[DropCanvas] Cannot drop container into itself or its descendant')
        emit('drag-end')
        return
      }
    } else if (data.fromNested) {
      // For nested moves, we need the actual component - check via parent chain
      // The actual check will be done in handleMoveChildToRoot/handleAddChildToContainer
    }

    if (data.fromPalette) {
      // New component from palette - add to specific tab
      const newComponent: CanvasComponent = {
        id: generateId(),
        componentId: `${data.type}_${Date.now()}`,
        type: data.type,
        label: data.label,
        props: data.defaultProps || {},
      }
      emit('add-child', containerId, newComponent, tabIndex)
    } else if (data.fromRoot) {
      // Root component → remove from root, then add to container
      // Save rootComp BEFORE deleting - don't re-lookup after delete
      const rootComp = props.components[data.index]
      if (rootComp) {
        emit('delete', rootComp.id)
        emit('add-child', containerId, rootComp, -1, tabIndex)
      }
    } else if (data.fromNested) {
      // Nested component → remove from source container, add to target
      // Save child BEFORE removing - don't re-lookup after remove
      const srcContainer = props.components.find(c => c.id === data.containerId)
      const child = srcContainer?.children?.[data.index]
      if (child) {
        emit('remove-child', data.containerId, child.componentId || child.id)
        emit('add-child', containerId, child, -1, tabIndex)
      }
    }
  } catch (err) {
    console.error('Failed to handle drop on tab:', err)
  }
  emit('drag-end')
}

// Container drop
const onContainerDrop = (e: DragEvent, containerId: string) => {
  if (isDroppingToTab.value) {
    isDroppingToTab.value = false
    return
  }
  e.preventDefault()
  e.stopPropagation()
  dragOverContainerId.value = null

  console.log('[DropCanvas] onContainerDrop called, containerId:', containerId)
  const data = e.dataTransfer?.getData('application/json')
  console.log('[DropCanvas] onContainerDrop data:', data)
  if (!data) {
    emit('drag-end')
    return
  }

  try {
    const parsed = JSON.parse(data)

    if (parsed.fromPalette) {
      // New component from palette - use temp id for client-side, backend will assign real id on save
      const newComponent: CanvasComponent = {
        id: generateId(),  // Temporary client-side id
        componentId: `${parsed.type}_${Date.now()}`, 
        type: parsed.type,
        label: parsed.label,
        props: parsed.defaultProps || {},
      }
      const tabIndex = parsed.type === 'tabs' ? (parsed.defaultProps?.activeTab as number || 0) : undefined
      emit('add-child', containerId, newComponent, dragOverIndex.value, tabIndex)
    } else if (parsed.fromRoot) {
      // Root component → remove from root, then add to container
      const comp = props.components[parsed.index]
      if (comp && isContainerType(comp.type) && isDescendantOf(containerId, comp.id)) {
        console.warn('[DropCanvas] Cannot drop container into itself or its descendant')
        emit('drag-end')
        return
      }
      emit('delete', comp.id)
      emit('add-child', containerId, comp, dragOverIndex.value)
    } else if (parsed.fromNested) {
      // Nested component → remove from source, add to target
      if (parsed.containerId !== containerId) {
        const srcContainer = props.components.find(c => c.id === parsed.containerId)
        const child = srcContainer?.children?.[parsed.index]
        if (child) {
          emit('remove-child', parsed.containerId, child.componentId || child.id)
          emit('add-child', containerId, child, dragOverIndex.value)
        }
      }
    }
  } catch (err) {
    console.error('Failed to parse drop data:', err)
  }
  emit('drag-end')
}

// Remove from container
const removeFromContainer = (containerId: string, childId: string) => {
  emit('remove-child', containerId, childId)
}

// Update component prop
const updateComponentProp = (id: string, key: string, value: any) => {
  emit('update-component', id, key, value)
}

// Expose for parent component
defineExpose({
  onPaletteDragStart,
  generateId,
})
</script>

<style scoped>
.nested-component {
  margin-left: 0;
}
</style>

// src/pages/editor/DropCanvas.tsx
import React, { useState, useRef, useCallback } from 'react';
import { View, ArrowUp, ArrowDown, Trash2, GripVertical } from 'lucide-react';
import { CanvasComponent } from './types';
import ComponentRenderer from './ComponentRenderer';

interface DropCanvasProps {
  components: CanvasComponent[];
  allComponents: CanvasComponent[];
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onReorder: (fromIndex: number, toIndex: number) => void;
  onDelete: (id: string) => void;
  onDrop: (e: React.DragEvent) => void;
  onAddChildToContainer: (containerId: string, component: CanvasComponent, tabIndex?: number) => void;
  onRemoveChildFromContainer?: (containerId: string, childId: string) => void;
  onMoveChildToRoot?: (containerId: string, childId: string, toIndex: number) => void;
  onResize?: (id: string, width: number, height: number) => void;
  onUpdateProps?: (id: string, props: Record<string, unknown>) => void;
  onDragStart?: () => void;
}

// Generate unique ID
export const generateId = () => `comp_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

function DropCanvas({
  components,
  allComponents,
  selectedId,
  onSelect,
  onReorder,
  onDelete,
  onDrop,
  onAddChildToContainer,
  onRemoveChildFromContainer,
  onMoveChildToRoot,
  onResize,
  onUpdateProps,
  onDragStart,
}: DropCanvasProps) {
  const [isDragOver, setIsDragOver] = useState(false);
  const [dragOverContainerId, setDragOverContainerId] = useState<string | null>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  
  // Track drag state
  const dragState = useRef<{
    dragType: 'new' | 'reorder' | 'nested';
    sourceId: string | null;
    sourceContainerId: string | null;
    sourceIndex: number;
  }>({
    dragType: 'new',
    sourceId: null,
    sourceContainerId: null,
    sourceIndex: -1,
  });

  const isContainerType = (type: string) => type === 'card' || type === 'tabs' || type === 'collapse';

  // Flatten components for reorder tracking - includes both root and nested
  const flattenComponents = useCallback((comps: CanvasComponent[], parentId: string | null = null): Array<{comp: CanvasComponent, parentId: string | null, index: number}> => {
    const result: Array<{comp: CanvasComponent, parentId: string | null, index: number}> = [];
    comps.forEach((comp, index) => {
      result.push({ comp, parentId, index });
      if (comp.children && comp.children.length > 0) {
        result.push(...flattenComponents(comp.children, comp.id));
      }
    });
    return result;
  }, []);

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    const rect = canvasRef.current?.getBoundingClientRect();
    if (rect) {
      const { clientX, clientY } = e;
      if (clientX < rect.left || clientX > rect.right || clientY < rect.top || clientY > rect.bottom) {
        setIsDragOver(false);
        setDragOverContainerId(null);
      }
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    setDragOverContainerId(null);
    onDrop(e);
  };

  const handleCanvasClick = (e: React.MouseEvent) => {
    if (e.target === canvasRef.current) {
      onSelect(null);
    }
  };

  // Handle drag start from palette (new component)
  const handlePaletteDragStart = (e: React.DragEvent, compType: string, compLabel: string, defaultProps?: Record<string, unknown>) => {
    dragState.current = {
      dragType: 'new',
      sourceId: null,
      sourceContainerId: null,
      sourceIndex: -1,
    };
    e.dataTransfer.setData('application/json', JSON.stringify({
      fromPalette: true,
      type: compType,
      label: compLabel,
      defaultProps,
    }));
  };

  // Handle drag start from root component (reorder)
  const handleRootDragStart = (e: React.DragEvent, index: number) => {
    dragState.current = {
      dragType: 'reorder',
      sourceId: null,
      sourceContainerId: null,
      sourceIndex: index,
    };
    e.dataTransfer.setData('application/json', JSON.stringify({
      fromRoot: true,
      index,
    }));
  };

  // Handle drag start from nested component (move out of container)
  const handleNestedDragStart = (e: React.DragEvent, containerId: string, index: number) => {
    dragState.current = {
      dragType: 'nested',
      sourceId: null,
      sourceContainerId: containerId,
      sourceIndex: index,
    };
    e.dataTransfer.setData('application/json', JSON.stringify({
      fromNested: true,
      containerId,
      index,
    }));
  };

  const handleContainerDragOver = (e: React.DragEvent, containerId: string) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOverContainerId(containerId);
  };

  const handleContainerDragLeave = (e: React.DragEvent) => {
    e.stopPropagation();
    // Only clear if leaving the container entirely
    const rect = e.currentTarget.getBoundingClientRect();
    const { clientX, clientY } = e;
    if (clientX < rect.left || clientX > rect.right || clientY < rect.top || clientY > rect.bottom) {
      setDragOverContainerId(null);
    }
  };

  const handleContainerDrop = (e: React.DragEvent, containerId: string, tabIndex?: number) => {
    e.preventDefault();
    e.stopPropagation();
    setDragOverContainerId(null);
    
    const data = e.dataTransfer.getData('application/json');
    if (!data) return;
    
    try {
      const parsed = JSON.parse(data);
      
      if (parsed.fromPalette) {
        // New component from palette
        const newComponent: CanvasComponent = {
          id: generateId(),
          componentId: `${parsed.type}_${Date.now()}`,
          type: parsed.type,
          label: parsed.label,
          props: parsed.defaultProps || {},
        };
        onAddChildToContainer(containerId, newComponent, tabIndex);
      } else if (parsed.fromRoot) {
        // Moving from root to container
        onMoveChildToRoot?.(containerId, '', parsed.index);
      } else if (parsed.fromNested) {
        // Moving from one container to another container
        if (parsed.containerId !== containerId) {
          onMoveChildToRoot?.(containerId, '', parsed.index);
        }
      }
    } catch (err) {
      console.error('Failed to parse drop data:', err);
    }
  };

  // Handle drop on canvas (for moving nested component to root)
  const handleRootDrop = (e: React.DragEvent, insertIndex?: number) => {
    const data = e.dataTransfer.getData('application/json');
    if (!data) return;
    
    try {
      const parsed = JSON.parse(data);
      
      if (parsed.fromNested && dragState.current.sourceContainerId) {
        // Moving nested component to root
        e.preventDefault();
        onMoveChildToRoot?.(dragState.current.sourceContainerId, '', insertIndex ?? -1);
      }
    } catch (err) {
      console.error('Failed to parse drop data:', err);
    }
  };

  // Render a single component item (used for both root and nested)
  const renderComponentItem = (
    comp: CanvasComponent, 
    index: number, 
    parentId: string | null,
    isNested: boolean
  ) => {
    const isSelected = selectedId === comp.id;
    const isDragOverContainer = dragOverContainerId === comp.id;
    
    return (
      <div
        key={comp.id}
        data-component-id={comp.id}
        draggable
        onDragStart={(e) => {
          if (parentId) {
            handleNestedDragStart(e, parentId, index);
          } else {
            handleRootDragStart(e, index);
          }
          onDragStart?.();
        }}
        onDragOver={(e) => e.preventDefault()}
        onClick={(e) => {
          e.stopPropagation();
          console.log('[DropCanvas] Click on component:', comp.id, 'isNested:', isNested);
          // Use setTimeout to ensure the click is not intercepted
          setTimeout(() => {
            onSelect(comp.id);
          }, 0);
        }}
        className={`relative bg-[var(--bg-primary)] border-2 rounded-md transition-all cursor-pointer group ${isNested ? 'nested-component' : ''} ${
          isSelected
            ? 'border-[var(--accent)] shadow-lg ring-2 ring-[var(--accent-light)]'
            : 'border-transparent hover:border-[var(--border)]'
        }`}
      >
        <div className="flex items-center gap-1 absolute -top-3 right-2 opacity-0 group-hover:opacity-100 transition-opacity z-10 bg-[var(--bg-primary)] rounded shadow">
          {!isNested && (
            <>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  if (index > 0) onReorder(index, index - 1);
                }}
                disabled={index === 0}
                className="p-1 border border-[var(--border)] rounded hover:bg-[var(--bg-hover)] disabled:opacity-30"
                title="上移"
              >
                <ArrowUp className="w-3 h-3" />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  if (index < components.length - 1) onReorder(index, index + 1);
                }}
                disabled={index === components.length - 1}
                className="p-1 border border-[var(--border)] rounded hover:bg-[var(--bg-hover)] disabled:opacity-30"
                title="下移"
              >
                <ArrowDown className="w-3 h-3" />
              </button>
            </>
          )}
          <button
            onClick={(e) => {
              e.stopPropagation();
              if (parentId && onRemoveChildFromContainer) {
                onRemoveChildFromContainer(parentId, comp.id);
              } else {
                onDelete(comp.id);
              }
            }}
            className="p-1 border border-[var(--danger)]/30 rounded hover:bg-[var(--danger)]/10 text-[var(--danger)]"
            title={isNested ? "移除" : "删除"}
          >
            <Trash2 className="w-3 h-3" />
          </button>
          <div className="p-1 border border-[var(--border)] rounded text-[var(--text-muted)] cursor-grab" title="拖拽">
            <GripVertical className="w-3 h-3" />
          </div>
        </div>
        
        <div className={`p-4 ${isContainerType(comp.type) ? 'pb-2' : ''}`}>
          <ComponentRenderer 
            component={comp} 
            allComponents={allComponents}
            onResize={onResize}
            onUpdateProps={onUpdateProps ? (props) => onUpdateProps(comp.id, props) : undefined}
          >
            {isContainerType(comp.type) && (
              <div 
                className={`min-h-16 border-2 border-dashed rounded m-2 p-2 transition-colors ${
                  isDragOverContainer 
                    ? 'border-[var(--accent)] bg-[var(--accent-light)]' 
                    : 'border-[var(--border)] bg-[var(--bg-secondary)] hover:border-[var(--accent)]'
                }`}
                onDragOver={(e) => handleContainerDragOver(e, comp.id)}
                onDragLeave={handleContainerDragLeave}
                onDrop={(e) => {
                  // For tabs, use the currently active tab index
                  const tabIndex = comp.type === 'tabs' ? (comp.props.activeTab as number || 0) : undefined;
                  handleContainerDrop(e, comp.id, tabIndex);
                }}
                onClick={(e) => {
                  e.stopPropagation();
                  onSelect(comp.id);
                }}
              >
                {/* Get children for drop zone - for tabs use childrenMap + comp.children, otherwise use children array */}
                {(() => {
                  let dropZoneChildren: CanvasComponent[] = [];
                  if (comp.type === 'tabs') {
                    // For tabs, children are in comp.children, but we filter by childrenMap
                    const childrenMap = comp.props.childrenMap as Record<string, string[]> | undefined;
                    if (childrenMap) {
                      const tabIndex = String(comp.props.activeTab || 0);
                      const childIds = childrenMap[tabIndex] || [];
                      // Filter comp.children by IDs in childrenMap[tabIndex]
                      dropZoneChildren = (comp.children || []).filter(c => childIds.includes(c.id));
                    } else {
                      // Fallback to all children if no childrenMap
                      dropZoneChildren = comp.children || [];
                    }
                  } else {
                    dropZoneChildren = comp.children || [];
                  }
                  
                  return dropZoneChildren.length > 0 ? (
                    <div className="flex flex-col gap-2">
                      {dropZoneChildren.map((child, childIndex) => 
                        renderComponentItem(child, childIndex, comp.id, true)
                      )}
                    </div>
                  ) : (
                    <div className="text-xs text-gray-400 text-center py-4">
                      拖拽组件到此处
                    </div>
                  );
                })()}
              </div>
            )}
          </ComponentRenderer>
        </div>
      </div>
    );
  };

  return (
    <div
      ref={canvasRef}
      onClick={handleCanvasClick}
      onDragOver={(e) => {
        handleDragOver(e);
        // Check if it's a nested component being dragged to root
        if (dragState.current.dragType === 'nested') {
          e.preventDefault();
        }
      }}
      onDragLeave={handleDragLeave}
      onDrop={(e) => {
        if (dragState.current.dragType === 'nested') {
          handleRootDrop(e);
        } else {
          handleDrop(e);
        }
      }}
      className={`flex-1 p-5 overflow-y-auto ${
        isDragOver ? 'bg-[var(--accent-light)] border-2 border-dashed border-[var(--accent)]' : 'bg-[var(--bg-secondary)]'
      }`}
    >
      {components.length === 0 ? (
        <div className="flex items-center justify-center min-h-96 bg-[var(--bg-primary)] border-2 border-dashed border-[var(--border)] rounded-lg">
          <div className="text-center text-[var(--text-muted)]">
            <View className="w-12 h-12 mx-auto mb-2 opacity-50" />
            <p>拖拽组件到此处构建页面</p>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          {components.map((comp, index) => 
            renderComponentItem(comp, index, null, false)
          )}
        </div>
      )}
    </div>
  );
}

export default DropCanvas;
