// src-vue/pages/dict/DictList.vue
<template>
  <div class="p-6">
    <!-- 页面标题 -->
    <div class="flex items-center justify-between mb-6">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center border border-blue-500/30">
          <el-icon size="20" color="var(--accent)"><Document /></el-icon>
        </div>
        <div>
          <h1 class="text-xl font-bold text-[var(--text-primary)]">数据字典管理</h1>
          <p class="text-xs text-[var(--text-muted)]">管理系统数据字典</p>
        </div>
      </div>
      <el-button type="primary" @click="handleCreate">
        <el-icon class="mr-1"><Plus /></el-icon> 新增
      </el-button>
    </div>

    <!-- 搜索栏 -->
    <div class="mb-4 bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] p-4">
      <div class="flex gap-4">
        <el-input
          v-model="searchName"
          placeholder="搜索字典名称..."
          clearable
          class="w-64"
          @keyup.enter="handleSearch"
        />
        <el-input
          v-model="searchCode"
          placeholder="搜索字典编码..."
          clearable
          class="w-64"
          @keyup.enter="handleSearch"
        />
        <el-button type="primary" @click="handleSearch">搜索</el-button>
      </div>
    </div>

    <!-- 列表 -->
    <div class="bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] overflow-hidden">
      <el-table :data="dicts" v-loading="loading" style="width: 100%">
        <el-table-column prop="code" label="字典编码" min-width="150">
          <template #default="{ row }">
            <span class="font-mono text-sm">{{ row.code }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="name" label="字典名称" min-width="150" />
        <el-table-column label="类型" width="100" align="center">
          <template #default="{ row }">
            {{ row.type === 'number' ? '数字' : '字符串' }}
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100" align="center">
          <template #default="{ row }">
            <el-tag :type="row.status === 1 ? 'success' : 'danger'" size="small">
              {{ row.status === 1 ? '启用' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="remark" label="备注" min-width="200">
          <template #default="{ row }">
            {{ row.remark || '-' }}
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150" fixed="right" align="center">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="handleEdit(row)">
              <el-icon><Edit /></el-icon>
            </el-button>
            <el-button link type="danger" size="small" @click="confirmDelete(row)">
              <el-icon><Delete /></el-icon>
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </div>

    <!-- 分页 -->
    <div class="mt-4 flex justify-between items-center">
      <div class="text-sm text-[var(--text-muted)]">共 {{ total }} 条记录</div>
      <el-pagination
        v-model:current-page="page"
        v-model:page-size="limit"
        :page-sizes="[10, 20, 50]"
        :total="total"
        layout="total, sizes, prev, pager, next"
        @current-change="loadDicts"
        @size-change="handleSizeChange"
      />
    </div>

    <!-- 删除确认弹窗 -->
    <el-dialog v-model="showDeleteConfirm" title="确认删除" width="400">
      <p>确定要删除该字典吗？此操作不可撤销。</p>
      <template #footer>
        <el-button @click="showDeleteConfirm = false">取消</el-button>
        <el-button type="danger" :loading="deleting" @click="handleDelete">删除</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { Document, Plus, Edit, Delete } from '@element-plus/icons-vue'
import { getDictList, deleteDict } from '@/lib/api'

interface Dict {
  id?: number
  code: string
  name: string
  type?: string
  remark?: string
  status?: number
}

const router = useRouter()

const dicts = ref<Dict[]>([])
const loading = ref(false)
const searchName = ref('')
const searchCode = ref('')
const page = ref(1)
const limit = ref(10)
const total = ref(0)
const showDeleteConfirm = ref(false)
const deleteId = ref<number | null>(null)
const deleting = ref(false)

async function loadDicts() {
  loading.value = true
  try {
    const data = await getDictList({
      name: searchName.value,
      code: searchCode.value,
      page: page.value,
      limit: limit.value
    })
    dicts.value = data.list
    total.value = data.total
  } catch (error) {
    console.error('Failed to load dicts:', error)
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  page.value = 1
  loadDicts()
}

function handleSizeChange() {
  page.value = 1
  loadDicts()
}

function handleCreate() {
  router.push('/dict/new')
}

function handleEdit(row: Dict) {
  router.push(`/dict/${row.id}`)
}

function confirmDelete(row: Dict) {
  deleteId.value = row.id!
  showDeleteConfirm.value = true
}

async function handleDelete() {
  if (!deleteId.value) return
  deleting.value = true
  try {
    await deleteDict(deleteId.value)
    ElMessage.success('删除成功')
    showDeleteConfirm.value = false
    deleteId.value = null
    // 如果当前页只有一条数据且不是第一页，则回到上一页
    if (dicts.value.length === 1 && page.value > 1) {
      page.value--
    }
    loadDicts()
  } catch (error) {
    console.error('Failed to delete dict:', error)
  } finally {
    deleting.value = false
  }
}

onMounted(() => {
  loadDicts()
})
</script>

// src/pages/DictList.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Edit2, Trash2, ChevronLeft, ChevronRight } from 'lucide-react';
import { getDictList, deleteDict } from '../lib/api';
import type { Dict } from '../types';

export default function DictList() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [dicts, setDicts] = useState<Dict[]>([]);
  const [searchName, setSearchName] = useState('');
  const [searchCode, setSearchCode] = useState('');
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    loadDicts();
  }, [page, limit]);

  const loadDicts = async () => {
    setLoading(true);
    try {
      const data = await getDictList({ page, limit, name: searchName, code: searchCode });
      setDicts(data.list);
      setTotal(data.total);
    } catch (error) {
      console.error('Failed to load dicts:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = () => {
    setPage(1);
    loadDicts();
  };

  const handleDelete = async (id: number) => {
    if (!confirm('确定要删除吗？')) return;
    try {
      await deleteDict(id);
      // 如果当前页只有一条数据且不是第一页，则回到上一页
      if (dicts.length === 1 && page > 1) {
        setPage(page - 1);
      } else {
        loadDicts();
      }
    } catch (error) {
      console.error('Failed to delete dict:', error);
    }
  };

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="p-4 h-full overflow-auto">
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-xl font-bold text-[var(--text-primary)]">数据字典管理</h1>
        <button
          onClick={() => navigate('/dict/new')}
          className="flex items-center gap-2 px-4 py-2 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg transition-colors"
        >
          <Plus className="w-4 h-4" />
          新增
        </button>
      </div>

      <div className="flex gap-4 mb-4">
        <input
          type="text"
          placeholder="搜索字典名称"
          value={searchName}
          onChange={(e) => setSearchName(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="px-3 py-2 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg text-[var(--text-primary)] text-sm focus:outline-none focus:border-[var(--accent-light)]"
        />
        <input
          type="text"
          placeholder="搜索字典编码"
          value={searchCode}
          onChange={(e) => setSearchCode(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="px-3 py-2 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg text-[var(--text-primary)] text-sm focus:outline-none focus:border-[var(--accent-light)]"
        />
        <button
          onClick={handleSearch}
          className="px-4 py-2 bg-[var(--accent)]/20 hover:bg-[var(--accent)]/30 text-[var(--accent)] rounded-lg transition-colors text-sm"
        >
          搜索
        </button>
      </div>

      <div className="bg-[var(--bg-table-header)] rounded-lg border border-[var(--border-light)] overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-[var(--border-light)] bg-[var(--bg-hover-light)]">
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">字典编码</th>
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">字典名称</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">类型</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">状态</th>
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">备注</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">操作</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={6} className="px-4 py-12 text-center text-[var(--text-muted)]">加载中...</td>
              </tr>
            ) : dicts.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-12 text-center text-[var(--text-muted)]">暂无数据</td>
              </tr>
            ) : (
              dicts.map(dict => (
                <tr key={dict.id} className="border-b border-[var(--border-light)] hover:bg-[var(--bg-hover-light)]">
                  <td className="px-4 py-3 text-sm text-[var(--text-primary)] font-mono">{dict.code}</td>
                  <td className="px-4 py-3 text-sm text-[var(--text-primary)]">{dict.name}</td>
                  <td className="px-4 py-3 text-center text-sm text-[var(--text-muted)]">
                    {dict.type === 'number' ? '数字' : '字符串'}
                  </td>
                  <td className="px-4 py-3 text-center">
                    <span className={`px-2 py-0.5 rounded text-xs ${dict.status === 1 ? 'bg-[var(--success)]/20 text-[var(--success)]' : 'bg-[var(--danger)]/20 text-[var(--danger)]'}`}>
                      {dict.status === 1 ? '启用' : '禁用'}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-sm text-[var(--text-muted)]">{dict.remark || '-'}</td>
                  <td className="px-4 py-3 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <button
                        onClick={() => navigate(`/dict/${dict.id}`)}
                        className="p-1.5 hover:bg-[var(--bg-tertiary)] rounded text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
                      >
                        <Edit2 className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(dict.id!)}
                        className="p-1.5 hover:bg-[var(--bg-tertiary)] rounded text-[var(--text-muted)] hover:text-[var(--danger)] transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* 分页组件 */}
      {total > 0 && (
        <div className="flex items-center justify-between mt-4 px-2">
          <div className="flex items-center gap-4">
            <span className="text-sm text-[var(--text-muted)]">共 {total} 条记录</span>
            <select
              value={limit}
              onChange={(e) => {
                setLimit(Number(e.target.value));
                setPage(1);
              }}
              className="px-2 py-1 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded text-sm text-[var(--text-primary)]"
            >
              <option value={5}>5条/页</option>
              <option value={10}>10条/页</option>
              <option value={20}>20条/页</option>
              <option value={50}>50条/页</option>
            </select>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage(page - 1)}
              disabled={page <= 1}
              className="p-1.5 rounded hover:bg-[var(--bg-tertiary)] text-[var(--text-muted)] hover:text-[var(--text-primary)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="text-sm text-[var(--text-primary)] px-2">{page} / {totalPages}</span>
            <button
              onClick={() => setPage(page + 1)}
              disabled={page >= totalPages}
              className="p-1.5 rounded hover:bg-[var(--bg-tertiary)] text-[var(--text-muted)] hover:text-[var(--text-primary)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
