// src/pages/PageList.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { getPageConfigList, deletePageConfig } from '../lib/api';

interface PageItem {
  id: number;
  name: string;
  code: string;
  description: string;
  status: number;
  createdAt: string;
  updatedAt: string;
}

const PageList: React.FC = () => {
  const navigate = useNavigate();
  const [pages, setPages] = useState<PageItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState('');

  const loadPages = async () => {
    setLoading(true);
    try {
      const res = await getPageConfigList({ page: 1, limit: 100, keyword: search });
      setPages(res.list);
    } catch (err) {
      console.error('加载页面列表失败', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPages();
  }, []);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    loadPages();
  };

  const handleDelete = async (id: number) => {
    if (!confirm('确定要删除这个页面吗？')) return;
    try {
      await deletePageConfig(id);
      loadPages();
    } catch (err) {
      console.error('删除失败', err);
    }
  };

  const handleEdit = (id: number) => {
    navigate(`/page-editor?pageId=${id}`);
  };

  const handleCreate = () => {
    navigate('/page-editor?new=true');
  };

  const handlePreview = (id: number) => {
    window.open(`#/preview?pageId=${id}`, '_blank');
  };

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">页面配置</h1>
        <button
          onClick={handleCreate}
          className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600"
        >
          新建页面
        </button>
      </div>

      <form onSubmit={handleSearch} className="mb-4 flex gap-2">
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="搜索页面名称或编码..."
          className="flex-1 px-3 py-2 border rounded"
        />
        <button type="submit" className="px-4 py-2 bg-gray-100 border rounded hover:bg-gray-200">
          搜索
        </button>
      </form>

      {loading ? (
        <div className="text-center py-8 text-gray-500">加载中...</div>
      ) : pages.length === 0 ? (
        <div className="text-center py-8 text-gray-500">暂无数据</div>
      ) : (
        <table className="w-full bg-white border rounded-lg overflow-hidden">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-3 text-left">ID</th>
              <th className="px-4 py-3 text-left">页面名称</th>
              <th className="px-4 py-3 text-left">页面编码</th>
              <th className="px-4 py-3 text-left">描述</th>
              <th className="px-4 py-3 text-left">状态</th>
              <th className="px-4 py-3 text-left">创建时间</th>
              <th className="px-4 py-3 text-left">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {pages.map((page) => (
              <tr key={page.id} className="hover:bg-gray-50">
                <td className="px-4 py-3">{page.id}</td>
                <td className="px-4 py-3">{page.name}</td>
                <td className="px-4 py-3">{page.code}</td>
                <td className="px-4 py-3 text-gray-500">{page.description || '-'}</td>
                <td className="px-4 py-3">
                  <span className={`px-2 py-1 rounded text-xs ${page.status === 1 ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'}`}>
                    {page.status === 1 ? '启用' : '禁用'}
                  </span>
                </td>
                <td className="px-4 py-3 text-gray-500">{page.updatedAt || page.createdAt}</td>
                <td className="px-4 py-3">
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleEdit(page.id)}
                      className="text-blue-500 hover:underline"
                    >
                      编辑
                    </button>
                    <button
                      onClick={() => handlePreview(page.id)}
                      className="text-green-500 hover:underline"
                    >
                      预览
                    </button>
                    <button
                      onClick={() => handleDelete(page.id)}
                      className="text-red-500 hover:underline"
                    >
                      删除
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
};

export default PageList;

// src/pages/PageList.vue
<template>
  <div class="page-list-page">
    <!-- Header -->
    <header class="page-header">
      <div class="header-left">
        <FileText class="header-icon" />
        <div class="header-text">
          <h1>页面配置</h1>
          <p>管理所有页面</p>
        </div>
      </div>
      <el-button type="primary" @click="handleCreate">
        <Plus class="btn-icon" />新建页面
      </el-button>
    </header>

    <!-- Table -->
    <div class="table-container">
      <el-table
        :data="pages"
        v-loading="loading"
        row-key="id"
        :header-cell-style="{ background: 'var(--bg-tertiary)', color: 'var(--text-secondary)', fontWeight: 500, fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em' }"
      >
        <el-table-column prop="id" label="ID" width="80" align="right" />
        <el-table-column prop="name" label="页面名称" min-width="180">
          <template #default="{ row }">
            <span class="page-name">{{ row.name }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="code" label="页面编码" min-width="150">
          <template #default="{ row }">
            <code class="page-code">{{ row.code }}</code>
          </template>
        </el-table-column>
        <el-table-column prop="description" label="描述" min-width="200" show-overflow-tooltip>
          <template #default="{ row }">
            <span class="description-text">{{ row.description || '—' }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="100" align="center">
          <template #default="{ row }">
            <span class="status-badge" :class="row.status === 1 ? 'status-active' : 'status-disabled'">
              {{ row.status === 1 ? '启用' : '禁用' }}
            </span>
          </template>
        </el-table-column>
        <el-table-column prop="updatedAt" label="更新时间" width="160">
          <template #default="{ row }">
            <span class="time-text">{{ row.updatedAt || '—' }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180" align="right" fixed="right">
          <template #default="{ row }">
            <div class="action-buttons">
              <el-button link size="small" type="primary" @click="handleEdit(row)">编辑</el-button>
              <el-button link size="small" type="primary" @click="handlePreview(row)">预览</el-button>
              <el-popconfirm title="确定删除？" @confirm="handleDelete(row.id)">
                <template #reference>
                  <el-button link size="small" type="danger">删除</el-button>
                </template>
              </el-popconfirm>
            </div>
          </template>
        </el-table-column>

        <template #empty>
          <div class="table-empty">
            <FileText class="empty-icon" />
            <p>暂无页面数据</p>
            <el-button type="primary" size="small" @click="handleCreate">创建第一个页面</el-button>
          </div>
        </template>
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, FileText } from 'lucide-vue-next'
import { getPageConfigList, deletePageConfig } from '@/lib/api'

interface PageItem {
  id: number
  name: string
  code: string
  description?: string
  status: number
  createdAt?: string
  updatedAt?: string
}

const router = useRouter()
const pages = ref<PageItem[]>([])
const loading = ref(false)

async function loadPages() {
  loading.value = true
  try {
    const data = await getPageConfigList({ page: 1, limit: 100 })
    pages.value = data.list || []
  } catch (error) {
    console.error('Failed to load pages:', error)
  } finally {
    loading.value = false
  }
}

function handleCreate() {
  router.push('/editor')
}

function handleEdit(row: PageItem) {
  router.push(`/editor?id=${row.id}`)
}

function handlePreview(row: PageItem) {
  window.open(`#/render/${row.code}`, '_blank')
}

async function handleDelete(id: number) {
  try {
    await deletePageConfig(id)
    ElMessage.success('删除成功')
    loadPages()
  } catch (error) {
    ElMessage.error('删除失败')
  }
}

onMounted(() => {
  loadPages()
})
</script>

<style scoped>
.page-list-page {
  padding: 24px;
  background: var(--bg-primary);
  min-height: 100vh;
}

/* Header */
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 24px;
}

.header-left {
  display: flex;
  align-items: center;
  gap: 16px;
}

.header-icon {
  width: 24px;
  height: 24px;
  color: var(--accent);
}

.header-text h1 {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
  margin: 0;
  letter-spacing: -0.01em;
}

.header-text p {
  font-size: 12px;
  color: var(--text-muted);
  margin: 2px 0 0;
}

.btn-icon {
  width: 14px;
  height: 14px;
  margin-right: 6px;
}

/* Table */
.table-container {
  background: var(--bg-secondary);
  border-radius: 10px;
  overflow: hidden;
}

:deep(.el-table) {
  --el-table-border-color: var(--border-light);
  --el-table-header-bg-color: var(--bg-tertiary);
  --el-table-row-hover-bg-color: var(--bg-hover);
  --el-table-bg-color: var(--bg-secondary);
  --el-table-tr-bg-color: var(--bg-secondary);
  --el-table-text-color: var(--text-primary);
}

:deep(.el-table th.el-table__cell) {
  padding: 12px 16px;
}

:deep(.el-table td.el-table__cell) {
  padding: 14px 16px;
  border-bottom: 1px solid var(--border-light);
}

:deep(.el-table__row:last-child td.el-table__cell) {
  border-bottom: none;
}

.page-name {
  font-weight: 500;
  color: var(--text-primary);
}

.page-code {
  font-family: 'SF Mono', Monaco, 'Courier New', monospace;
  font-size: 12px;
  padding: 2px 6px;
  background: var(--bg-tertiary);
  border-radius: 4px;
  color: var(--text-secondary);
}

.description-text {
  color: var(--text-secondary);
  font-size: 13px;
}

.time-text {
  font-size: 13px;
  color: var(--text-muted);
}

/* Status Badge */
.status-badge {
  display: inline-flex;
  align-items: center;
  padding: 2px 10px;
  border-radius: 12px;
  font-size: 12px;
  font-weight: 500;
}

.status-active {
  background: color-mix(in srgb, var(--success) 15%, transparent);
  color: var(--success);
}

.status-disabled {
  background: color-mix(in srgb, var(--text-muted) 15%, transparent);
  color: var(--text-muted);
}

/* Action Buttons */
.action-buttons {
  display: flex;
  gap: 4px;
  justify-content: flex-end;
}

/* Empty State */
.table-empty {
  padding: 60px 20px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 12px;
}

.empty-icon {
  width: 32px;
  height: 32px;
  color: var(--text-muted);
  opacity: 0.4;
}

.table-empty p {
  font-size: 14px;
  color: var(--text-muted);
  margin: 0;
}
</style>
