// src-vue/pages/SystemConfigList.vue
<template>
  <div class="config-page p-6">
    <!-- 页面标题 -->
    <div class="mb-6">
      <h1 class="text-2xl font-bold text-[var(--text-primary)]">系统参数</h1>
    </div>

    <!-- 搜索条件 -->
    <div class="mb-4 bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] p-4">
      <el-form :inline="true" :model="searchForm" class="flex flex-wrap gap-4 items-end">
        <el-form-item label="参数名称" class="flex-1 min-w-[200px]">
          <el-input v-model="searchForm.name" placeholder="搜索参数名称" clearable @keyup.enter="handleSearch" />
        </el-form-item>
        <el-form-item label="参数编码">
          <el-input v-model="searchForm.code" placeholder="搜索参数编码" clearable @keyup.enter="handleSearch" />
        </el-form-item>
        <el-form-item label="分组">
          <el-input v-model="searchForm.groupName" placeholder="搜索分组" clearable @keyup.enter="handleSearch" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="handleSearch">搜索</el-button>
          <el-button @click="handleReset">重置</el-button>
        </el-form-item>
      </el-form>
    </div>

    <!-- 数据表格 -->
    <div class="bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] p-4">
      <div class="flex justify-between items-center mb-4">
        <span class="text-sm text-[var(--text-muted)]">共 {{ total }} 条</span>
        <el-button type="primary" @click="handleCreate">
          <el-icon class="mr-1"><Plus /></el-icon>
          新增参数
        </el-button>
      </div>

      <el-table v-loading="loading" :data="configs" stripe style="width: 100%">
        <el-table-column prop="id" label="ID" width="80" />
        <el-table-column prop="name" label="参数名称" min-width="150" />
        <el-table-column prop="code" label="参数编码" width="180" />
        <el-table-column prop="groupName" label="分组" width="120" />
        <el-table-column prop="value" label="参数值" min-width="150" show-overflow-tooltip />
        <el-table-column prop="type" label="类型" width="80" />
        <el-table-column prop="sort" label="排序" width="60" />
        <el-table-column prop="status" label="状态" width="80">
          <template #default="{ row }">
            <el-tag :type="row.status === 1 ? 'success' : 'danger'" size="small">
              {{ row.status === 1 ? '启用' : '停用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="150" fixed="right">
          <template #default="{ row }">
            <el-button size="small" text type="primary" @click="handleEdit(row)">编辑</el-button>
            <el-button size="small" text type="danger" @click="handleDelete(row.id)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <!-- 分页 -->
      <div class="flex justify-end mt-4">
        <el-pagination
          v-model:current-page="page"
          v-model:page-size="limit"
          :page-sizes="[10, 20, 50, 100]"
          :total="total"
          layout="total, sizes, prev, pager, next"
          @size-change="handleSizeChange"
          @current-change="handlePageChange"
        />
      </div>
    </div>

    <!-- 编辑弹窗 -->
    <el-dialog
      v-model="dialogVisible"
      :title="dialogMode === 'create' ? '新增参数' : '编辑参数'"
      width="500px"
    >
      <el-form :model="formData" label-width="100px">
        <el-form-item label="参数名称" required>
          <el-input v-model="formData.name" placeholder="请输入参数名称" />
        </el-form-item>
        <el-form-item label="参数编码" required>
          <el-input v-model="formData.code" placeholder="请输入参数编码" />
        </el-form-item>
        <el-form-item label="分组">
          <el-input v-model="formData.groupName" placeholder="请输入分组" />
        </el-form-item>
        <el-form-item label="参数值" required>
          <el-input v-model="formData.value" placeholder="请输入参数值" />
        </el-form-item>
        <el-form-item label="类型">
          <el-select v-model="formData.type" placeholder="请选择" class="w-full">
            <el-option label="文本" value="text" />
            <el-option label="数字" value="number" />
            <el-option label="布尔" value="boolean" />
            <el-option label="JSON" value="json" />
          </el-select>
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="formData.sort" :min="0" class="w-full" />
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="formData.description" type="textarea" :rows="2" placeholder="请输入描述" />
        </el-form-item>
        <el-form-item label="状态">
          <el-radio-group v-model="formData.status">
            <el-radio :label="1">启用</el-radio>
            <el-radio :label="0">停用</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" :loading="saving" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { getSystemConfigList, saveSystemConfig, deleteSystemConfig } from '@/lib/api'

interface SystemConfig {
  id?: number
  name?: string
  code?: string
  value?: string
  type?: string
  groupName?: string
  description?: string
  sort?: number
  status?: number
}

const configs = ref<SystemConfig[]>([])
const loading = ref(false)
const total = ref(0)
const page = ref(1)
const limit = ref(10)

const searchForm = reactive({
  name: '',
  code: '',
  groupName: '',
})

const dialogVisible = ref(false)
const dialogMode = ref<'create' | 'edit'>('create')
const saving = ref(false)

const formData = reactive<SystemConfig>({
  name: '',
  code: '',
  value: '',
  type: 'text',
  groupName: '',
  description: '',
  sort: 0,
  status: 1,
})

async function loadData() {
  loading.value = true
  try {
    const data = await getSystemConfigList({
      page: page.value,
      limit: limit.value,
      name: searchForm.name || undefined,
      code: searchForm.code || undefined,
      groupName: searchForm.groupName || undefined,
    })
    configs.value = data.list || []
    total.value = data.total || 0
  } catch (error) {
    console.error('Failed to load configs:', error)
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  page.value = 1
  loadData()
}

function handleReset() {
  searchForm.name = ''
  searchForm.code = ''
  searchForm.groupName = ''
  page.value = 1
  loadData()
}

function handleSizeChange() {
  page.value = 1
  loadData()
}

function handlePageChange() {
  loadData()
}

function handleCreate() {
  dialogMode.value = 'create'
  Object.assign(formData, {
    id: undefined,
    name: '',
    code: '',
    value: '',
    type: 'text',
    groupName: '',
    description: '',
    sort: 0,
    status: 1,
  })
  dialogVisible.value = true
}

function handleEdit(row: SystemConfig) {
  dialogMode.value = 'edit'
  Object.assign(formData, row)
  dialogVisible.value = true
}

async function handleSave() {
  if (!formData.name || !formData.code || !formData.value) {
    ElMessage.warning('请填写必填项')
    return
  }
  saving.value = true
  try {
    await saveSystemConfig(formData)
    ElMessage.success(dialogMode.value === 'create' ? '创建成功' : '更新成功')
    dialogVisible.value = false
    loadData()
  } catch (error: any) {
    ElMessage.error(error.message || '保存失败')
  } finally {
    saving.value = false
  }
}

async function handleDelete(id: number) {
  try {
    await ElMessageBox.confirm('确定要删除该参数吗？', '提示', { type: 'warning' })
    await deleteSystemConfig(id)
    ElMessage.success('删除成功')
    if (configs.value.length === 1 && page.value > 1) {
      page.value--
    }
    loadData()
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
    }
  }
}

onMounted(() => {
  loadData()
})
</script>

<style scoped>
.config-page {
  background: var(--bg-primary);
  min-height: 100%;
}
</style>

// src/pages/SystemConfigList.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, Edit2, Trash2, ChevronLeft, ChevronRight } from 'lucide-react';
import { getSystemConfigList, deleteSystemConfig } from '../lib/api';
import type { SystemConfig } from '../types';

export default function SystemConfigList() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);
  const [configs, setConfigs] = useState<SystemConfig[]>([]);
  const [searchName, setSearchName] = useState('');
  const [searchCode, setSearchCode] = useState('');
  const [searchGroup, setSearchGroup] = useState('');
  const [groups, setGroups] = useState<string[]>([]);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    loadConfigs();
  }, [page, limit]);

  const loadConfigs = async () => {
    setLoading(true);
    try {
      const data = await getSystemConfigList({ page, limit, name: searchName, code: searchCode, groupName: searchGroup });
      setConfigs(data.list);
      setTotal(data.total);
      // 从列表中提取分组
      const groupSet = new Set<string>();
      data.list.forEach(c => c.groupName && groupSet.add(c.groupName));
      setGroups(Array.from(groupSet));
    } catch (error) {
      console.error('Failed to load configs:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm('确定要删除吗？')) return;
    try {
      await deleteSystemConfig(id);
      // 如果当前页只有一条数据且不是第一页，则回到上一页
      if (configs.length === 1 && page > 1) {
        setPage(page - 1);
      } else {
        loadConfigs();
      }
    } catch (error) {
      console.error('Failed to delete config:', error);
    }
  };

  const handleSearch = () => {
    setPage(1);
    loadConfigs();
  };

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="p-4 h-full overflow-auto">
      <div className="flex items-center justify-between mb-4">
        <h1 className="text-xl font-bold text-[var(--text-primary)]">系统参数管理</h1>
        <button
          onClick={() => navigate('/config/new')}
          className="flex items-center gap-2 px-4 py-2 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg transition-colors"
        >
          <Plus className="w-4 h-4" />
          新增
        </button>
      </div>

      <div className="flex gap-4 mb-4">
        <input
          type="text"
          placeholder="搜索参数名称"
          value={searchName}
          onChange={(e) => setSearchName(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="px-3 py-2 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg text-[var(--text-primary)] text-sm focus:outline-none focus:border-[var(--accent-light)]"
        />
        <input
          type="text"
          placeholder="搜索参数编码"
          value={searchCode}
          onChange={(e) => setSearchCode(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
          className="px-3 py-2 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg text-[var(--text-primary)] text-sm focus:outline-none focus:border-[var(--accent-light)]"
        />
        <select
          value={searchGroup}
          onChange={(e) => setSearchGroup(e.target.value)}
          className="px-3 py-2 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg text-[var(--text-primary)] text-sm focus:outline-none focus:border-[var(--accent-light)]"
        >
          <option value="">全部分组</option>
          {groups.map(group => (
            <option key={group} value={group}>{group}</option>
          ))}
        </select>
        <button
          onClick={handleSearch}
          className="px-4 py-2 bg-[var(--accent)]/20 hover:bg-[var(--accent)]/30 text-[var(--accent)] rounded-lg transition-colors text-sm"
        >
          搜索
        </button>
      </div>

      <div className="bg-[var(--bg-table-header)] rounded-lg border border-[var(--border-light)] overflow-hidden">
        <table className="w-full">
          <thead>
            <tr className="border-b border-[var(--border-light)] bg-[var(--bg-hover-light)]">
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">参数编码</th>
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">参数名称</th>
              <th className="px-4 py-3 text-left text-sm font-medium text-[var(--text-muted)]">参数值</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">类型</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">分组</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">状态</th>
              <th className="px-4 py-3 text-center text-sm font-medium text-[var(--text-muted)]">操作</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={7} className="px-4 py-12 text-center text-[var(--text-muted)]">加载中...</td>
              </tr>
            ) : configs.length === 0 ? (
              <tr>
                <td colSpan={7} className="px-4 py-12 text-center text-[var(--text-muted)]">暂无数据</td>
              </tr>
            ) : (
              configs.map(config => (
                <tr key={config.id} className="border-b border-[var(--border-light)] hover:bg-[var(--bg-hover-light)]">
                  <td className="px-4 py-3 text-sm text-[var(--text-primary)] font-mono">{config.code}</td>
                  <td className="px-4 py-3 text-sm text-[var(--text-primary)]">{config.name}</td>
                  <td className="px-4 py-3 text-sm text-[var(--text-muted)] font-mono max-w-xs truncate">{config.value}</td>
                  <td className="px-4 py-3 text-center text-sm text-[var(--text-muted)]">
                    {config.type === 'string' ? '字符串' : config.type === 'number' ? '数字' : '布尔'}
                  </td>
                  <td className="px-4 py-3 text-center text-sm text-[var(--text-muted)]">{config.groupName || '-'}</td>
                  <td className="px-4 py-3 text-center">
                    <span className={`px-2 py-0.5 rounded text-xs ${config.status === 1 ? 'bg-[var(--success)]/20 text-[var(--success)]' : 'bg-[var(--danger)]/20 text-[var(--danger)]'}`}>
                      {config.status === 1 ? '启用' : '禁用'}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <button
                        onClick={() => navigate(`/config/${config.id}`)}
                        className="p-1.5 hover:bg-[var(--bg-tertiary)] rounded text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
                      >
                        <Edit2 className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => handleDelete(config.id!)}
                        className="p-1.5 hover:bg-[var(--bg-tertiary)] rounded text-[var(--text-muted)] hover:text-[var(--danger)] transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* 分页组件 */}
      {total > 0 && (
        <div className="flex items-center justify-between mt-4 px-2">
          <div className="flex items-center gap-4">
            <span className="text-sm text-[var(--text-muted)]">共 {total} 条记录</span>
            <select
              value={limit}
              onChange={(e) => {
                setLimit(Number(e.target.value));
                setPage(1);
              }}
              className="px-2 py-1 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded text-sm text-[var(--text-primary)]"
            >
              <option value={5}>5条/页</option>
              <option value={10}>10条/页</option>
              <option value={20}>20条/页</option>
              <option value={50}>50条/页</option>
            </select>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setPage(page - 1)}
              disabled={page <= 1}
              className="p-1.5 rounded hover:bg-[var(--bg-tertiary)] text-[var(--text-muted)] hover:text-[var(--text-primary)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
            </button>
            <span className="text-sm text-[var(--text-primary)] px-2">{page} / {totalPages}</span>
            <button
              onClick={() => setPage(page + 1)}
              disabled={page >= totalPages}
              className="p-1.5 rounded hover:bg-[var(--bg-tertiary)] text-[var(--text-muted)] hover:text-[var(--text-primary)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
