// src-vue/pages/tasks/TaskList.vue
<template>
  <div class="p-6">
    <!-- 标题 -->
    <div class="flex justify-between items-center mb-6">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/20 to-purple-500/20 flex items-center justify-center border border-blue-500/30">
          <RefreshCw class="w-5 h-5 text-blue-500" />
        </div>
        <div>
          <h1 class="text-xl font-bold text-[var(--text-primary)] dark:text-white">任务管理</h1>
          <p class="text-xs text-[var(--text-muted)] dark:text-gray-400">配置ETL同步任务</p>
        </div>
      </div>
      <el-button type="primary" @click="handleCreate">
        <Plus class="w-4 h-4 mr-1" /> 新增
      </el-button>
    </div>

    <!-- 搜索筛选 -->
    <div class="bg-[var(--bg-secondary)] dark:bg-gray-800 rounded-xl border border-[var(--border-light)] dark:border-gray-700 p-4 mb-6">
      <div class="flex gap-4 flex-wrap">
        <el-input
          v-model="searchTable"
          placeholder="支持表名称查询"
          clearable
          class="w-64"
        />
        <el-input
          v-model="searchName"
          placeholder="支持任务名称模糊查询"
          clearable
          class="w-64"
        />
        <el-button type="primary" @click="loadData">查询</el-button>
        <el-button @click="resetSearch">重置</el-button>
      </div>
    </div>

    <!-- 任务列表 -->
    <div class="bg-[var(--bg-secondary)] dark:bg-gray-800 rounded-xl border border-[var(--border-light)] dark:border-gray-700 overflow-hidden">
      <el-table :data="filteredTasks" v-loading="loading" stripe style="width: 100%">
        <el-table-column prop="name" label="任务名称" min-width="150" />
        <el-table-column prop="target_table" label="目标表" min-width="120" />
        <el-table-column label="同步频率" width="150">
          <template #default="{ row }">
            {{ row.window_value }} {{ row.window_unit === 'minutes' ? '分钟' : row.window_unit === 'hours' ? '小时' : '天' }}
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag :type="row.status === 1 ? 'success' : 'info'" size="small">
              {{ row.status === 1 ? '启用' : '禁用' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="200" fixed="right">
          <template #default="{ row }">
            <el-button link type="primary" size="small" @click="handleToggle(row)">
              {{ row.status === 1 ? '禁用' : '启用' }}
            </el-button>
            <el-button link type="primary" size="small" @click="handleEdit(row)">编辑</el-button>
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { Plus, RefreshCw } from 'lucide-vue-next'
import { ElMessage } from 'element-plus'
import axios from 'axios'

interface Task {
  id?: number
  name: string
  target_table: string
  window_value?: number
  window_unit?: string
  status?: number
}

const API_BASE = '/etl-admin'
const api = axios.create({
  baseURL: API_BASE,
  timeout: 10000,
})

api.interceptors.request.use((config) => {
  const token = localStorage.getItem('token')
  if (token) {
    config.headers['Authorization'] = `Bearer ${token}`
  }
  return config
})

async function getTasks(): Promise<Task[]> {
  const res = await api.post('/simple/queryTaskListPage', { page: 1, limit: 20 })
  if (res.data?.code === 0 || res.data?.code === 1) {
    return res.data?.list || []
  }
  return []
}

async function toggleTask(id: number): Promise<void> {
  await api.post('/simple/updateStatus', { id })
}

const router = useRouter()
const tasks = ref<Task[]>([])
const loading = ref(false)
const searchTable = ref('')
const searchName = ref('')

const filteredTasks = computed(() => {
  return tasks.value.filter(task => {
    const matchTable = !searchTable.value || task.target_table.toLowerCase().includes(searchTable.value.toLowerCase())
    const matchName = !searchName.value || task.name.toLowerCase().includes(searchName.value.toLowerCase())
    return matchTable && matchName
  })
})

onMounted(() => {
  loadData()
})

async function loadData() {
  loading.value = true
  try {
    const data = await getTasks()
    tasks.value = data
  } catch (error) {
    console.error('Failed to load tasks:', error)
  } finally {
    loading.value = false
  }
}

async function handleToggle(row: Task) {
  if (!row.id) return
  try {
    await toggleTask(row.id)
    ElMessage.success('操作成功')
    loadData()
  } catch (error) {
    console.error('Failed to toggle task:', error)
  }
}

function handleCreate() {
  router.push('/tasks/new')
}

function handleEdit(row: Task) {
  router.push(`/tasks/${row.id}`)
}

function resetSearch() {
  searchTable.value = ''
  searchName.value = ''
  loadData()
}
</script>

// src/pages/TaskList.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, RefreshCw, ToggleLeft, ToggleRight } from 'lucide-react';
import { getTasks, toggleTask } from '../lib/api';
import type { Task } from '../types';

export default function TaskList() {
  const navigate = useNavigate();
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTable, setSearchTable] = useState('');
  const [searchName, setSearchName] = useState('');

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    setLoading(true);
    try {
      const data = await getTasks();
      setTasks(data);
    } catch (error) {
      console.error('Failed to load tasks:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleToggle = async (id: number) => {
    await toggleTask(id);
    loadData();
  };

  const filteredTasks = tasks.filter(task => {
    const matchTable = !searchTable || task.target_table.toLowerCase().includes(searchTable.toLowerCase());
    const matchName = !searchName || task.name.toLowerCase().includes(searchName.toLowerCase());
    return matchTable && matchName;
  });

  const getIntervalText = (task: Task) => {
    return `${task.window_value} ${task.window_unit === 'minutes' ? 'MINUTES' : task.window_unit === 'hours' ? 'HOURS' : 'DAYS'}`;
  };

  return (
    <div className="p-6">
      {/* 标题 */}
      <div className="flex justify-between items-center mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[var(--accent-light)] to-pink-500/20 flex items-center justify-center border border-[var(--accent-light)]">
            <RefreshCw className="w-5 h-5 text-[var(--accent)]" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-[var(--text-primary)]">任务管理</h1>
            <p className="text-xs text-[var(--text-muted)]">配置ETL同步任务</p>
          </div>
        </div>
        <button
          onClick={() => navigate('/tasks/new')}
          className="flex items-center gap-2 px-4 py-2 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg transition-colors"
        >
          <Plus className="w-4 h-4" />
          新增
        </button>
      </div>

      {/* 搜索筛选 */}
      <div className="bg-[var(--bg-secondary)]/60 backdrop-blur-xl rounded-xl border border-[var(--border-light)] p-4 mb-6">
        <div className="flex gap-4">
          <div className="flex-1">
            <input
              type="text"
              value={searchTable}
              onChange={(e) => setSearchTable(e.target.value)}
              placeholder="支持表名称查询"
              className="w-full px-4 py-2.5 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/30 text-sm text-[var(--text-input)] placeholder:text-[var(--text-muted)]"
            />
          </div>
          <div className="flex-1">
            <input
              type="text"
              value={searchName}
              onChange={(e) => setSearchName(e.target.value)}
              placeholder="支持任务名称模糊查询"
              className="w-full px-4 py-2.5 bg-[var(--bg-hover-light)] border border-[var(--border-light)] rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/30 text-sm text-[var(--text-input)] placeholder:text-[var(--text-muted)]"
            />
          </div>
          <button
            onClick={loadData}
            className="px-4 py-2.5 bg-[var(--accent)] hover:bg-[var(--accent-hover)] text-white rounded-lg transition-colors"
          >
            查询
          </button>
          <button
            onClick={() => { setSearchTable(''); setSearchName(''); }}
            className="px-4 py-2.5 bg-[var(--bg-tertiary)] text-[var(--text-primary)] rounded-lg hover:bg-[var(--bg-hover)] transition-colors"
          >
            重置
          </button>
        </div>
      </div>

      {/* 表格 */}
      <div className="bg-[var(--bg-secondary)]/60 backdrop-blur-xl rounded-xl border border-[var(--border-light)] overflow-hidden">
        <table className="w-full">
          <thead className="bg-[var(--bg-table-header)]">
            <tr>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">任务名称</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">源库</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">目标库</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">目标表</th>
              <th className="px-4 py-3 text-center text-xs font-medium text-[var(--text-muted)] uppercase">状态</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">执行间隔</th>
              <th className="px-4 py-3 text-left text-xs font-medium text-[var(--text-muted)] uppercase">上次执行时间</th>
              <th className="px-4 py-3 text-center text-xs font-medium text-[var(--text-muted)] uppercase">操作</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[var(--border-light)]">
            {loading ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-[var(--text-muted)]">
                  加载中...
                </td>
              </tr>
            ) : filteredTasks.length === 0 ? (
              <tr>
                <td colSpan={8} className="px-4 py-8 text-center text-[var(--text-muted)]">
                  暂无数据
                </td>
              </tr>
            ) : (
              filteredTasks.map((task) => (
                <tr key={task.id} className="hover:bg-[var(--bg-table-header)] transition-colors">
                  <td className="px-4 py-3 text-[var(--text-primary)] truncate font-medium">{task.name}</td>
                  <td className="px-4 py-3 text-[var(--text-muted)] truncate">{task.source_name}</td>
                  <td className="px-4 py-3 text-[var(--text-secondary)] truncate">{task.target_name || 'nr_data'}</td>
                  <td className="px-4 py-3 text-cyan-400 font-mono text-sm truncate max-w-[200px]">
                    {task.target_table}
                  </td>
                  <td className="px-4 py-3 text-center">
                    <button
                      onClick={() => handleToggle(task.id)}
                      className={`transition-colors ${task.status === 1 ? 'text-[var(--info)]' : 'text-[var(--text-muted)]'}`}
                    >
                      {task.status === 1 ? (
                        <ToggleRight className="w-8 h-6" />
                      ) : (
                        <ToggleLeft className="w-8 h-6" />
                      )}
                    </button>
                  </td>
                  <td className="px-4 py-3">
                    <span className="px-2 py-1 bg-[var(--accent-light)] text-[var(--accent)] rounded text-xs">
                      {getIntervalText(task)}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-[var(--text-muted)] truncate text-sm">
                    {task.last_run_time || '-'}
                  </td>
                  <td className="px-4 py-3">
                    <div className="flex items-center justify-center gap-2">
                      <button
                        onClick={() => navigate(`/tasks/${task.id}`)}
                        className="px-3 py-1.5 bg-[var(--info)]/10 text-[var(--info)] rounded hover:bg-[var(--info)]/20 transition-colors text-sm"
                      >
                        编辑
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
