// src/pages/ApiList.tsx
import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Plus, RefreshCw, Edit, Trash2, Play, Copy, Search, ChevronRight, ChevronDown, Database, Table } from 'lucide-react';
import { getDataSources, getTableList, getApiList, deleteApi, toggleApi, testApi } from '../lib/api';
import type { DataSource, ApiConfig, TableInfo } from '../types';

// 树节点类型
interface TreeNode {
  id: string;
  name: string;
  type: 'datasource' | 'table';
  dataType?: string;
  databaseName?: string;
  tableName?: string;
  children?: TreeNode[];
  isLeaf?: boolean;
  isLoading?: boolean;
}

export default function ApiList() {
  const navigate = useNavigate();
  const [datasources, setDatasources] = useState<DataSource[]>([]);
  const [apiList, setApiList] = useState<ApiConfig[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [selectedDs, setSelectedDs] = useState<number | null>(null);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);
  const [searchKeyword, setSearchKeyword] = useState('');
  
  // 树相关状态
  const [treeData, setTreeData] = useState<TreeNode[]>([]);
  const [expandedKeys, setExpandedKeys] = useState<Set<string>>(new Set());

  useEffect(() => {
    loadDataSources();
  }, []);

  useEffect(() => {
    loadApiList();
  }, [selectedDs, selectedTable, searchKeyword]);

  const loadDataSources = async () => {
    try {
      const data = await getDataSources();
      setDatasources(data);
      // 构建树形结构
      const tree = data.map(ds => ({
        id: `ds_${ds.id}`,
        name: ds.name,
        type: 'datasource' as const,
        dataType: ds.dataType,
        databaseName: ds.databaseName,
        children: [],
        isLeaf: false
      }));
      setTreeData(tree);
    } catch (error) {
      console.error('Failed to load datasources:', error);
    }
  };

  const loadApiList = async () => {
    setLoading(true);
    try {
      const params: any = { page: 1, limit: 20 };
      if (selectedDs) params.datasourceId = selectedDs;
      if (selectedTable) params.tableName = selectedTable;
      if (searchKeyword) params.keyword = searchKeyword;
      
      const result = await getApiList(params);
      setApiList(result.list);
      setTotal(result.total);
    } catch (error) {
      console.error('Failed to load API list:', error);
    } finally {
      setLoading(false);
    }
  };

  // 展开/收起节点
  const handleExpand = async (node: TreeNode) => {
    const key = node.id;
    const newExpanded = new Set(expandedKeys);
    
    if (newExpanded.has(key)) {
      newExpanded.delete(key);
      setExpandedKeys(newExpanded);
      return;
    }
    
    newExpanded.add(key);
    setExpandedKeys(newExpanded);
    
    // 懒加载表
    if (node.type === 'datasource' && node.databaseName) {
      // 找到对应节点并标记加载状态
      const updateTree = (nodes: TreeNode[]): TreeNode[] => {
        return nodes.map(n => {
          if (n.id === key) {
            return { ...n, isLoading: true };
          }
          if (n.children) {
            return { ...n, children: updateTree(n.children) };
          }
          return n;
        });
      };
      setTreeData(prev => updateTree(prev));
      
      // 加载表
      try {
        const tables = await getTableList(node.databaseName);
        const tableNodes: TreeNode[] = tables.map((t: TableInfo) => ({
          id: `table_${node.id}_${t.tableName}`,
          name: t.tableName + (t.tableComment ? ` (${t.tableComment})` : ''),
          type: 'table' as const,
          tableName: t.tableName,
          databaseName: node.databaseName,
          isLeaf: true
        }));
        
        const updateTreeWithTables = (nodes: TreeNode[]): TreeNode[] => {
          return nodes.map(n => {
            if (n.id === key) {
              return { ...n, children: tableNodes, isLoading: false };
            }
            if (n.children) {
              return { ...n, children: updateTreeWithTables(n.children) };
            }
            return n;
          });
        };
        setTreeData(prev => updateTreeWithTables(prev));
      } catch (error) {
        console.error('Failed to load tables:', error);
      }
    }
  };

  // 选择节点
  const handleSelect = (node: TreeNode) => {
    if (node.type === 'datasource') {
      const ds = datasources.find(d => d.id === parseInt(node.id.replace('ds_', '')));
      if (ds) {
        setSelectedDs(ds.id);
        setSelectedTable(null);
      }
    } else if (node.type === 'table') {
      // 找到父节点的数据源
      const parentId = node.id.split('_').slice(0, 2).join('_');
      const dsId = parseInt(parentId.replace('ds_', ''));
      setSelectedDs(dsId);
      setSelectedTable(node.tableName || null);
    }
  };

  // 获取当前选中节点的信息
  const getSelectedNodeInfo = () => {
    if (selectedTable) {
      const ds = datasources.find(d => d.id === selectedDs);
      return ds ? `${ds.name} / ${selectedTable}` : '';
    }
    if (selectedDs) {
      const ds = datasources.find(d => d.id === selectedDs);
      return ds ? ds.name : '';
    }
    return '';
  };

  const handleDelete = async (id: number) => {
    if (confirm('确定要删除该API吗？')) {
      await deleteApi(id);
      loadApiList();
    }
  };

  const handleToggle = async (api: ApiConfig) => {
    const newStatus = api.status === 1 ? 0 : 1;
    await toggleApi(api.id!, newStatus);
    loadApiList();
  };

  const handleTest = async (id: number) => {
    try {
      const result = await testApi(id, {});
      alert(JSON.stringify(result, null, 2));
    } catch (error: any) {
      alert('测试失败: ' + (error.message || '未知错误'));
    }
  };

  const handleCopy = (api: ApiConfig) => {
    // TODO: 复制功能
    alert('复制功能开发中');
  };

  // 递归渲染树节点
  const renderTreeNode = (node: TreeNode, level: number = 0) => {
    const isExpanded = expandedKeys.has(node.id);
    const isSelected = (node.type === 'datasource' && selectedDs === parseInt(node.id.replace('ds_', ''))) ||
                      (node.type === 'table' && selectedTable === node.tableName);
    
    return (
      <div key={node.id}>
        <div
          className={`flex items-center gap-2 px-3 py-2 cursor-pointer hover:bg-slate-700/50 ${
            isSelected ? 'bg-blue-500/20 text-blue-400' : 'text-slate-300'
          }`}
          style={{ paddingLeft: `${level * 16 + 12}px` }}
          onClick={() => handleSelect(node)}
        >
          {node.type === 'datasource' && !node.isLeaf && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                handleExpand(node);
              }}
              className="p-0.5 hover:bg-slate-600 rounded"
            >
              {isExpanded ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
            </button>
          )}
          {node.type === 'datasource' ? (
            <Database className="w-4 h-4 text-blue-400" />
          ) : (
            <Table className="w-4 h-4 text-green-400" />
          )}
          <span className="text-sm truncate">{node.name}</span>
          {node.isLoading && <RefreshCw className="w-3 h-3 animate-spin" />}
        </div>
        {isExpanded && node.children && (
          <div>
            {node.children.map(child => renderTreeNode(child, level + 1))}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex h-full">
      {/* 左侧树 */}
      <div className="w-64 bg-[#1e293b]/60 border-r border-slate-700/50 flex flex-col">
        <div className="p-4 border-b border-slate-700/50">
          <div className="flex items-center gap-2 text-slate-400">
            <Database className="w-4 h-4" />
            <span className="text-sm font-medium">数据源与表</span>
          </div>
        </div>
        <div className="flex-1 overflow-auto p-2">
          {treeData.map(node => renderTreeNode(node))}
        </div>
      </div>

      {/* 右侧内容 */}
      <div className="flex-1 p-6 overflow-auto">
        {/* 标题 */}
        <div className="flex justify-between items-center mb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500/20 to-pink-500/20 flex items-center justify-center border border-purple-500/20">
              <Table className="w-5 h-5 text-purple-400" />
            </div>
            <div>
              <h1 className="text-xl font-bold text-white">API管理</h1>
              <p className="text-xs text-slate-500">
                {getSelectedNodeInfo() || '全部API'}
              </p>
            </div>
          </div>
          <Link
            to="/apis/new"
            className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-500 to-pink-600 text-white rounded-xl hover:opacity-90 transition-opacity"
          >
            <Plus className="w-4 h-4" />
            新增API
          </Link>
        </div>

        {/* 搜索筛选 */}
        <div className="bg-[#1e293b]/60 backdrop-blur-xl rounded-xl border border-slate-700/50 p-4 mb-6">
          <div className="flex gap-4">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500" />
              <input
                type="text"
                value={searchKeyword}
                onChange={(e) => setSearchKeyword(e.target.value)}
                placeholder="搜索API名称或路径"
                className="w-full pl-10 pr-4 py-2.5 bg-slate-800/50 border border-slate-700/50 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500/30 text-sm text-slate-200 placeholder-slate-600"
              />
            </div>
            <button
              onClick={loadApiList}
              className="px-4 py-2.5 bg-purple-500 text-white rounded-lg hover:bg-purple-600 transition-colors"
            >
              <RefreshCw className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* 表格 */}
        <div className="bg-[#1e293b]/60 backdrop-blur-xl rounded-xl border border-slate-700/50 overflow-hidden">
          <table className="w-full">
            <thead className="bg-slate-800/30">
              <tr>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">API名称</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">路径</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">方法</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">数据源</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">表</th>
                <th className="px-4 py-3 text-left text-xs font-medium text-slate-400 uppercase">状态</th>
                <th className="px-4 py-3 text-center text-xs font-medium text-slate-400 uppercase">操作</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-700/50">
              {loading ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-slate-400">
                    加载中...
                  </td>
                </tr>
              ) : apiList.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-4 py-8 text-center text-slate-400">
                    暂无数据
                  </td>
                </tr>
              ) : (
                apiList.map((api) => (
                  <tr key={api.id} className="hover:bg-slate-800/30 transition-colors">
                    <td className="px-4 py-3 text-white font-medium">{api.name}</td>
                    <td className="px-4 py-3 text-slate-300 font-mono text-sm">{api.path}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs ${
                        api.method === 'GET' ? 'bg-green-500/20 text-green-400' : 'bg-blue-500/20 text-blue-400'
                      }`}>
                        {api.method}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-slate-300">{api.datasourceName}</td>
                    <td className="px-4 py-3 text-slate-300">{api.tableName}</td>
                    <td className="px-4 py-3">
                      <span className={`px-2 py-1 rounded text-xs ${api.status === 1 ? 'bg-green-500/20 text-green-400' : 'bg-slate-600/20 text-slate-400'}`}>
                        {api.status === 1 ? '启用' : '禁用'}
                      </span>
                    </td>
                    <td className="px-4 py-3">
                      <div className="flex items-center justify-center gap-2">
                        <button
                          onClick={() => handleTest(api.id!)}
                          className="p-2 hover:bg-green-500/10 rounded-lg text-green-400 transition-colors"
                          title="测试"
                        >
                          <Play className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleCopy(api)}
                          className="p-2 hover:bg-purple-500/10 rounded-lg text-purple-400 transition-colors"
                          title="复制"
                        >
                          <Copy className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => navigate(`/apis/${api.id}`)}
                          className="p-2 hover:bg-blue-500/10 rounded-lg text-blue-400 transition-colors"
                          title="编辑"
                        >
                          <Edit className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleToggle(api)}
                          className="p-2 hover:bg-yellow-500/10 rounded-lg text-yellow-400 transition-colors"
                          title={api.status === 1 ? '禁用' : '启用'}
                        >
                          {api.status === 1 ? <Trash2 className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// src-vue/pages/ApiList.vue
<template>
  <div class="api-list p-4 h-full flex gap-4">
    <!-- 左侧数据源树 -->
    <div class="w-64 flex-shrink-0 bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] flex flex-col">
      <div class="p-3 border-b border-[var(--border-light)]">
        <h3 class="text-sm font-medium text-[var(--text-primary)]">数据源</h3>
      </div>
      <div class="flex-1 overflow-auto p-2">
        <el-tree
          :data="datasourceTree"
          :props="{ label: 'name', children: 'children' }"
          node-key="id"
          :default-expand-all="true"
          @node-click="handleNodeClick"
          class="datasource-tree"
        />
      </div>
    </div>

    <!-- 右侧 API 列表 -->
    <div class="flex-1 bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-light)] flex flex-col">
      <div class="p-4 border-b border-[var(--border-light)]">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-lg font-bold text-[var(--text-primary)]">API 管理</h2>
          <el-button type="primary" @click="handleCreate">新增 API</el-button>
        </div>
        <div class="flex gap-4">
          <el-input v-model="searchName" placeholder="API 名称" clearable @keyup.enter="handleSearch" class="w-48" />
          <el-input v-model="searchPath" placeholder="API 路径" clearable @keyup.enter="handleSearch" class="w-48" />
          <el-button type="primary" @click="handleSearch">搜索</el-button>
        </div>
      </div>

      <div class="flex-1 overflow-auto p-4">
        <el-table v-loading="loading" :data="apiList" stripe style="width: 100%">
          <el-table-column prop="id" label="ID" width="80" />
          <el-table-column prop="name" label="API 名称" min-width="150" />
          <el-table-column prop="path" label="路径" width="180" />
          <el-table-column prop="method" label="方法" width="80">
            <template #default="{ row }">
              <el-tag :type="row.method === 'GET' ? 'success' : row.method === 'POST' ? 'primary' : 'warning'" size="small">
                {{ row.method || 'POST' }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="datasourceName" label="数据源" width="120" />
          <el-table-column prop="tableName" label="表名" width="120" />
          <el-table-column prop="status" label="状态" width="80">
            <template #default="{ row }">
              <el-tag :type="row.status === 1 ? 'success' : 'danger'" size="small">
                {{ row.status === 1 ? '启用' : '停用' }}
              </el-tag>
            </template>
          </el-table-column>
          <el-table-column label="操作" width="200" fixed="right">
            <template #default="{ row }">
              <el-button size="small" text type="primary" @click="handleEdit(row)">编辑</el-button>
              <el-button size="small" text type="primary" @click="handleTest(row)">测试</el-button>
              <el-button size="small" text type="danger" @click="handleDelete(row.id)">删除</el-button>
            </template>
          </el-table-column>
        </el-table>
      </div>
    </div>

    <!-- 测试弹窗 -->
    <el-dialog v-model="testDialogVisible" title="测试 API" width="800px">
      <div v-if="testingApi" class="space-y-4">
        <div class="text-sm text-[var(--text-secondary)]">
          <span class="font-medium">{{ testingApi.name }}</span>
          <span class="ml-2 text-[var(--text-muted)]">{{ testingApi.method }} {{ testingApi.path }}</span>
        </div>
        
        <div>
          <h4 class="text-sm font-medium mb-2">输入参数</h4>
          <el-input v-model="testParams" type="textarea" :rows="4" placeholder="JSON 格式，如: {&quot;id&quot;: 1}" />
        </div>

        <div>
          <h4 class="text-sm font-medium mb-2">返回结果</h4>
          <div v-if="testLoading" class="text-center py-8 text-[var(--text-muted)]">加载中...</div>
          <pre v-else-if="testResult" class="bg-[var(--bg-tertiary)] p-4 rounded text-xs overflow-auto max-h-64">{{ testResult }}</pre>
          <div v-else class="text-center py-8 text-[var(--text-muted)]">点击执行查看结果</div>
        </div>
      </div>
      <template #footer>
        <el-button @click="testDialogVisible = false">关闭</el-button>
        <el-button type="primary" :loading="testLoading" @click="executeTest">执行</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getApiList, getApiDetail, deleteApi, testApi, getDataSources, getTableList } from '@/lib/api'

interface ApiItem {
  id: number
  name: string
  path: string
  method: string
  datasourceId?: number
  datasourceName?: string
  databaseName?: string
  tableName?: string
  description?: string
  status: number
}

interface TreeNode {
  id: string | number
  name: string
  type: 'datasource' | 'table'
  children?: TreeNode[]
}

const apiList = ref<ApiItem[]>([])
const datasourceTree = ref<TreeNode[]>([])
const loading = ref(false)
const searchName = ref('')
const searchPath = ref('')
const selectedDatasourceId = ref<number>()

// 测试相关
const testDialogVisible = ref(false)
const testingApi = ref<ApiItem | null>(null)
const testParams = ref('')
const testResult = ref('')
const testLoading = ref(false)

async function loadDatasources() {
  try {
    const res = await getDataSources({ page: 1, limit: 100 })
    const tree: TreeNode[] = []
    if (res.list) {
      for (const ds of res.list) {
        tree.push({
          id: `ds_${ds.id}`,
          name: ds.name || ds.dbName || `数据源${ds.id}`,
          type: 'datasource',
          children: []
        })
      }
    }
    datasourceTree.value = tree
  } catch (error) {
    console.error('Failed to load datasources:', error)
  }
}

async function loadApis() {
  loading.value = true
  try {
    const res = await getApiList({
      page: 1,
      limit: 100,
      datasourceId: selectedDatasourceId.value,
      name: searchName.value || undefined,
      path: searchPath.value || undefined
    })
    apiList.value = res.list || []
  } catch (error) {
    console.error('Failed to load API list:', error)
  } finally {
    loading.value = false
  }
}

function handleSearch() {
  loadApis()
}

function handleNodeClick(data: TreeNode) {
  if (data.type === 'datasource') {
    selectedDatasourceId.value = Number(data.id.toString().replace('ds_', ''))
    loadApis()
  }
}

function handleCreate() {
  ElMessage.info('请使用 React 版本创建 API')
}

function handleEdit(row: ApiItem) {
  ElMessage.info('请使用 React 版本编辑 API')
}

async function handleTest(row: ApiItem) {
  testingApi.value = row
  testParams.value = ''
  testResult.value = ''
  testDialogVisible.value = true
}

async function executeTest() {
  if (!testingApi.value) return
  testLoading.value = true
  testResult.value = ''
  try {
    let params = {}
    if (testParams.value) {
      try {
        params = JSON.parse(testParams.value)
      } catch {
        ElMessage.error('参数 JSON 格式错误')
        testLoading.value = false
        return
      }
    }
    const res = await testApi(testingApi.value.id, params)
    testResult.value = JSON.stringify(res, null, 2)
  } catch (error: any) {
    testResult.value = `Error: ${error.message || '测试失败'}`
  } finally {
    testLoading.value = false
  }
}

async function handleDelete(id: number) {
  try {
    await ElMessageBox.confirm('确定要删除该 API 吗？', '提示', { type: 'warning' })
    await deleteApi(id)
    ElMessage.success('删除成功')
    loadApis()
  } catch (error: any) {
    if (error !== 'cancel') {
      ElMessage.error('删除失败')
    }
  }
}

onMounted(() => {
  loadDatasources()
  loadApis()
})
</script>

<style scoped>
.api-list {
  background: var(--bg-primary);
  min-height: calc(100vh - 60px);
}
:deep(.datasource-tree) {
  background: transparent;
}
:deep(.el-tree-node__content) {
  height: 32px;
}
</style>
